### ISSUE TITLE
EKS + Raft + Istio = Hang

### ISSUE THREAD

**Issue by GJKrupa** [hashicorp/vault#10317]
**Describe the bug**
We are testing migration from Consul to Raft storage in an Istio-enabled EKS cluster. When running in this configuration, all of the Vault server nodes hang indefinitely on startup about 90% of the time and no log output is produced even with log_level set to "Trace". We are using the standard hashicorp/vault Helm chart.

**To Reproduce**
1. Deploy with the following Helm values file in an Istio-enabled cluster with sidecar injection and mTLS enabled:
```yaml
injector:
  enabled: false

server:

  logLevel: Trace

  annotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "false"

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m

  ingress:
    enabled: false

  dataStorage:
    size: 5G

  standalone:
    enabled: false

  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        log_level = "Trace"

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

        seal "awskms" {
          region     = "REDACTED"  
          kms_key_id = "REDACTED"
        }

  serviceAccount:
    name: vault-test-sa
```

**Expected behavior**
The Vault server nodes come up (at least enough to be able to run operator init and operator raft join

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.4
* Vault CLI Version (retrieve with `vault version`): 1.5.4
* Server Operating System/Architecture: EKS v1.18.8-eks-7c9bda

Vault server configuration file(s):

See above Helm values yaml

**Additional context**
The nodes come up fine (after about 2 minutes) if the Istio sidecar injector is not present. If the Vault server pods are repeatedly deleted, they will occasionally come up and go into a Ready state but it usually takes at least 7 or 8 restarts and I've not seen more than one of them go Ready at the same time.
