### ISSUE TITLE
Vault AWS Login does not respect aws client config endpoints

### ISSUE THREAD

**Issue by emmaroberts-nbs** [hashicorp/vault#10438]
**Describe the bug**
When configuring the vault docker image to point to aws localstack docker image for local testing, the `vault login -method=aws` does not honour the configured endpoints and defaults to https://sts.amazonaws.com/

**To Reproduce**
Steps to reproduce the behaviour:
_**Files needed**_
#### **`run.sh`**
```bash
docker-compose -f docker-compose.yml up -d
echo "Sleeping while waiting for dependencies to come up"
sleep 18
vault_docker_name=$(docker ps -f "health=healthy" -f "ancestor=vault" --format "{{.Names}}")
echo "${vault_docker_name}"
if [[ ! -z ${vault_docker_name} ]]; then
    echo "Configuring vault"
    echo "Enabling aws auth"
    docker exec ${vault_docker_name} sh -c "vault login rootToken; vault auth enable aws;"
    echo "Configuring aws auth"
    curl --header "X-Vault-Token: rootToken" --request POST --data '{"access_key":"foo", "secret_key":"bar", "endpoint":"http://localstack:4566", "iam_endpoint":"http://localstack:4566", "sts_endpoint":"http://localstack:4566", "sts_region":"eu-west-2"}'  http://localhost:8200/v1/auth/aws/config/client
    echo "Seeding secrets"
    docker exec ${vault_docker_name} sh -c "vault secrets enable -path=secrets/ kv; vault kv put secrets/data/rediscachesecrets redisApiKey=redis"
fi
```
#### **`docker-compose.yml`**
```yml
version: '3.4'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
    volumes:
      - ./seed.yaml:/init/seed.yaml
    environment:
      SERVICES: "sqs,kms,iam,sts"
      DEFAULT_REGION: "eu-west-2"
  vault:
    depends_on:
      - localstack
    image: vault:latest
    container_name: vault
    command: server -dev
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", }'
      VAULT_SEAL_TYPE: "awskms"
      AWS_KMS_ENDPOINT: "http://localstack:4566"
      AWS_REGION: "eu-west-2"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      AWS_SESSION_TOKEN: "test"
      VAULT_AWSKMS_SEAL_KEY_ID: "bc436485-5092-42b8-92a3-0aa8b93536dc"
      VAULT_DEV_ROOT_TOKEN_ID: "rootToken"
    healthcheck:
      test: [ "CMD", "wget", "-S", "--spider", "http://localhost:8200/v1/sys/health" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
```
#### **`seed.yaml`**
```yaml
Keys:
  Symmetric:
    Aes:
      - Metadata:
          KeyId: bc436485-5092-65442b8-92a3-0aa8b93536dc
        BackingKeys:
          - 5cdaead27fe7da2de47945d73cd6d79e36494e73802f3cd3869f1d2cb0b5d7a9

Aliases:
  - AliasName: alias/testing
    TargetKeyId: bc436485-5092-65442b8-92a3-0aa8b93536dc
```
1. Run `./run.sh`
1. Exec info vault docker `docker exec -it vault sh`
2. Run `vault login -method=aws region=eu-west-2`
3. Error: 
```
Error authenticating: Error making API request.

URL: PUT http://0.0.0.0:8200/v1/auth/aws/login
Code: 400. Errors:

* error making upstream request: body of GetCallerIdentity is invalid
```
5. Now generate the curl string and decode the url: `vault login -method=aws -output-curl-string region=eu-west-2`

**Expected behaviour**
The iam_request_url should be the endpoint specified in the aws config client which in my case was http://localstack:4566 except the result is https//sts.amazonaws.com

**Environment:**
```bash
# vault status
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.6.0
Storage Type             file
Cluster Name             vault-cluster-3a885ab1
Cluster ID               94b01fef-c0bc-eed8-ac27-d830c78cdc00
HA Enabled               false
/ # vault version
Vault v1.6.0 (7ce0bd9691998e0443bc77e98b1e2a4ab1e965d4)
```
* Server Operating System/Architecture: docker image provided by vault version 1.6.0
