### ISSUE TITLE
Agent injection : Forbidden: pod updates may not add or remove containers

### ISSUE THREAD

**Issue by pbriet** [hashicorp/vault#11064]
**Describe the bug**
At one point, the K8S injection stops working correctly. Pods are stuck in "ContainerCreating" state, with the following error :   `failed to set annotation on pod xxx: Pod "xxx" is invalid: spec.containers: Forbidden: pod updates may not add or remove containers`

It fails on any Deployment  (see example below). But curiously, it does not when creating pods directly.

Tried to restart the injection agent, but no change.

**To Reproduce**
Not sure. It happenened twice, in two separate OKD clusters.
1- Playing some time with Vault with success
2- Disabling Vault injection on the given deployment (removing annotations)
3- Re-enabling Vault injection
4- Failure  (even when creating other deployments)

Once in failure state, it always reproducible.

**Expected behavior**
Should continue to inject my secrets

**Environment:**
* Vault Server Version : 1.6.2
* Vault CLI Version :  1.6.2
* Server Operating System/Architecture: K8S on OKD 4.7

**Example of failing deployment**

Pretty simple one :
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: failure
  namespace: app-experiments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failure
  template:
    metadata:
      labels:
        app: failure
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: default-experiment
        vault.hashicorp.com/agent-inject-secret-s3-credentials: secret/experiments/file-manager
        
    spec:
      containers:
        - resources:
          name: test
          image: public.ecr.aws/bitnami/nginx:latest
```

But the following Pod spec works correctly : 
 ```
kind: Pod
apiVersion: v1
metadata:
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-secret-s3-credentials: secret/experiments/file-manager
    vault.hashicorp.com/role: default-experiment
  name: success-single-pod
  namespace: app-experiments
spec:
  containers:
    - name: test
      image: 'public.ecr.aws/bitnami/nginx:latest'
 ```

Vault Agent is correctly injected, and secrets mounted.
