### ISSUE TITLE
Support for shutting down Vault Agent when Job ends (possibly via HTTP POST)

### ISSUE THREAD

**Issue by cpick** [hashicorp/vault#11089]
**Is your feature request related to a problem? Please describe.**
We have several long-running Kubernetes batch/v1 Jobs that require credentials from an injected `vault agent`.  The token and credentials need to be renewed throughout the life of the Job and should be revoked when the Job ends (via [vault-k8s](https://github.com/hashicorp/vault-k8s)s "vault.hashicorp.com/agent-revoke-on-shutdown" annotation).

Currently, the Jobs never finish because agent's container will continue to live on indefinitely even after the Job's "main" container finishes its work and exits.

**Describe the solution you'd like**
We'd like to have a mechanism for telling the injected vault agent to shut down.

We also run Istio in our cluster and its `istio-proxy` sidecar (which is an `envoy` proxy under the hood) has a similar issue.  The Istio project has worked around this problem by having it run a [HTTP listener](https://github.com/istio/istio/issues/15041) which gracefully exits when it receives a `POST /quitquitquit`.

Additional tooling has grown up around this convention, including the [`scuttle` helper](https://github.com/redboxllc/scuttle) which wraps the execution of the Job's "main" process and issues `POST` requests to each of the Pod's sidecars asking them to shut down.

I'd love to be able to configure the vault agent sidecar to listen for a POST on some path and cleanly shut down if/when it receives one.

**Describe alternatives you've considered**
We currently use a custom fork of the aforementioned `scuttle` command to `pkill -SIGINT vault-sidekick` but this forces us to relax our security settings by setting `shareProcessNamespace: true` and to run both the sidecar and main process under the same user.

We cannot use vault-k8s' "vault.hashicorp.com/agent-pre-populate-only" annotation (as suggested in [another issue](https://github.com/hashicorp/vault-k8s/issues/120#issuecomment-612442641)) because without the agent running as a sidecar the token/credentials would expire before the main Job completes (and could live beyond its completion since they're not actively revoked).

The same underlying issue has come up with `consul-k8s` and it looks like it's [adding a similar endpoint](https://github.com/hashicorp/consul-k8s/issues/162).

Envoy's [underlying endpoint](https://www.envoyproxy.io/docs/envoy/latest/operations/admin.html?highlight=quitquitquit#post--quitquitquit).

In the future this *might* be solved by Kubernetes allowing [dependencies between containers within a Pod to be specified](https://github.com/kubernetes/kubernetes/issues/65502), but that discussion has been ongoing for 2.5 years and the appropriate teams have not reached consensus on the shape/scope of the solution.

**Additional context**
I would be happy to help implement a solution if this sounds like a good idea.

I originally requested this over in the [vault-k8s repo](https://github.com/hashicorp/vault-k8s/issues/217), they [seemed interested](https://github.com/hashicorp/vault-k8s/issues/217#issuecomment-771175938), but pointed out that this would be a Vault Agent feature and redirected me here.

**Comment by HridoyRoy** [comment]
Hi @cpick ,

I think this is would be a great feature to have! I'm going to pass this along to the ecosystem team to see what they think! (cc @calvn ). 
Thanks!

**Comment by RetroDreams** [comment]
Do we know if there is any update on this request? I work for a multinational Fortune 100 (more closer to Fortune 50) corporation that could greatly benefit from this feature in our K8s ecosystem.

**Comment by treyhendon** [comment]
We had problems with our Helm jobs (database migrations) and the Vault Agents recently, so we ended up pulling the Vault Agent from the Jobs and replaced it by running a script as our entry point to curl the Vault API and set the necessary variables for our migrations to complete.  This way, our jobs didn't get hung because the sidecar did not shut down.  If it's helpful, here's the (not very pretty) container command:

`command: [ "bash", "-c", 'while [ ! -f /var/run/secrets/kubernetes.io/serviceaccount/token ];do sleep 1; done && LOGIN_DATA=$(curl --request POST --header "Content-Type: application/json" --data "{\"role\":\"$VAULT_ROLE\",\"jwt\":\"$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"}" $VAULT_ADDR/v1/auth/kubernetes/login) && [[ "$LOGIN_DATA" =~ $REGEX_TOKEN ]] && VAULT_TOKEN="${BASH_REMATCH[1]}" && CREDS=$(curl --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/database/creds/$VAULT_ROLE) && [[ "$CREDS" =~ $REGEX_USER ]] && USER="${BASH_REMATCH[1]}" && export POSTGRES__USER="${USER}{{ .Values.postgres.userPostfix }}" && [[ "$CREDS" =~ $REGEX_PASSWORD ]] && PASSWORD="${BASH_REMATCH[1]}" && export POSTGRES__PASSWORD="$PASSWORD" && /liquibase/run-db-migrations.sh {{ include "chart.name" . }} {{ .Values.application.version }} && curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST $VAULT_ADDR/v1/auth/token/revoke-self && curl -X POST http://localhost:15020/quitquitquit' ]`

The normal entry for the container is `/liquibase/run-db-migrations.sh`.  Everything prior to that completely replaced the Vault Sidecar.  (Also, notice the Istio `/quitquitquit` at the end.)

**Comment by nawarajshahi** [comment]
I had a very similar situation with job successfully running the task but failing to gracefully terminate the agent. However, I was able to have job terminate the agent container by adding the following along with all other annotations. 
```
vault.hashicorp.com/agent-pre-populate-only: "true"
```
Hopefully this helps!

**Comment by blhagadorn** [comment]
+1 to this

**Comment by dexterlakin** [comment]
FYI There is a workarounwhich is to disable the sidecar container with this annotation :

`vault.hashicorp.com/agent-pre-populate-only : "true"`

If the jobs are short-lived and it's not critical if they fail because a secret was changed, then the sidecar isn't required.

**Comment by andreapigatto** [comment]
Hi, I'm in a similar scenario where I would need to have the sidecar running till the main container of my job is completed.
@tomhjp thanks for the endpoint `/agent/v1/quit`. Btw being a bit newbie with k8s, I'm having some issues to understand how to call it.
I deployed vault via bitnami helm chart and I'm using the vault agent injector approach. No problem to retrieve the secrets in my job main container. 
As described on documentation I set this extra annotation to enable the endpoint in the configuration.

`vault.hashicorp.com/agent-enable-quit: "true"`

So my pod annotations look like:

```
  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "vault"
    vault.hashicorp.com/agent-cache-enable: "true"
    vault.hashicorp.com/agent-cache-use-auto-auth-token: "force"
    vault.hashicorp.com/agent-log-level: "debug"
    vault.hashicorp.com/agent-enable-quit: "true"
    vault.hashicorp.com/agent-inject-secret-global-config.json: "global/data/config"
    vault.hashicorp.com/agent-inject-template-global-config.json: |
      {{- with secret "global/data/config" -}}
      {{ .Data | toUnescapedJSON }}
      {{- end -}}
```

Is it enough for the vault agent configuration or something else should be set to make `/agent/v1/quit` available?

My job is running in the same namespace of vault as a post-install hook:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-cmd-job
  annotations:
    "helm.sh/hook": post-install, post-upgrade
spec:
  template:
    metadata:
      {{- with .Values.job.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: wait-container
        image: andreapigatto/busybox-curl:1.37.0
        command: ["/bin/sh", "-c", "/vault/userconfig/scripts/post-job-script.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /vault/userconfig/scripts
      restartPolicy: Never
      serviceAccountName: vault-job
      volumes:
      - name: script-volume
        configMap:
          name: job-script
          defaultMode: 0777
  backoffLimit: 2
```

and this is the script that is running:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-script
data:
  post-job-script.sh: |
    echo "Waiting for manual secrets to be added..."

    # Initialize sleep time (seconds) and maximum sleep limit
    sleep_time=5
    max_sleep_time=300

    # Path to JSON file
    json_file="/vault/secrets/global-config.json"

    # Extracting specific values from the JSON file using jq
    SECRETS_LOADED=$(/tmp/jq -r '.data.SECRETS_LOADED' "$json_file")

    while true; do
      # Check the 'proceed' value from the confirmation file
      if [ "$SECRETS_LOADED" = "true" ]; then
        echo "Confirmation received. Manual secrets added successfully."
        break
      fi

      # Notify waiting duration and sleep
      echo "Confirmation not yet received. Waiting for ${sleep_time}s..."
      sleep "$sleep_time"

      # Double the sleep time, capped at the maximum limit
      sleep_time=$((sleep_time < max_sleep_time ? sleep_time * 2 : max_sleep_time))
    done
```

Basically the main idea is to wait listening for the vault secret SECRETS_LOADED to be true. Once this happen main container will terminate. All good with this logic apart that the vault agent is hanging running indefinitely keeping even the job running.

For this reason I would like to be able to shutdown the vault agent with `/agent/v1/quit` at the end of my script.
My idea would be to add a curl to `/agent/v1/quit` before the break. 
Issue is that I don't know exactly which service to use to refer to the vault agent.

I have these services running, part of vault and part of vault-agent:

```
NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/vault                      ClusterIP   10.245.246.225   <none>        8200/TCP,8201/TCP   8m46s
service/vault-active               ClusterIP   10.245.66.11     <none>        8200/TCP,8201/TCP   8m46s
service/vault-agent-injector-svc   ClusterIP   10.245.92.57     <none>        443/TCP             8m46s
service/vault-internal             ClusterIP   None             <none>        8200/TCP,8201/TCP   8m46s
service/vault-standby              ClusterIP   10.245.209.23    <none>        8200/TCP,8201/TCP   8m46s
service/vault-ui                   ClusterIP   10.245.204.163   <none>        8200/TCP            8m46s
```

These are the pods running:

```
NAME                                       READY   STATUS     RESTARTS   AGE
pod/vault-0                                1/1     Running    0          8m46s
pod/vault-1                                1/1     Running    0          8m46s
pod/vault-2                                1/1     Running    0          8m46s
pod/vault-agent-injector-bdbbcb8cf-tvmm2   1/1     Running    0          8m46s
pod/wait-for-cmd-job-ptm94                 1/2     NotReady   0          7m52s
```
as you see last pod is my job and contains the main container plus the vault agent generated via vault injector. I think the 1 container pending is the vault agent still running.

I tried to add to my script referring to vault or vault-agent-injector-svc in this way:

`curl --request POST --header "X-Vault-Token: $VAULT_TOKEN" http://vault/v1/agent/v1/quit`
`curl --request POST --header "X-Vault-Token: $VAULT_TOKEN" http://vault-agent-injector-svc/v1/agent/v1/quit`

but is not working. How can I point to the vault agent in this scenario?

Any hints? Thanks!
