### ISSUE TITLE
persistent dev mode

### ISSUE THREAD

**Issue by MichaelSp** [hashicorp/vault#12004]
**Is your feature request related to a problem? Please describe.**
I need an easy, restart-able, **persistent** development setup. 

**Describe the solution you'd like**
I need a `dev` mode with persistence that I can write in a simple `docker-compose`.

**Describe alternatives you've considered**
1. Writing a script to do the unsealing automatically. But just for my dev-setup that's too much work to maintain.
2. I tried this setup:
```yaml
services:
  vault:
    image: vault:latest
    ports:
    - "8200:8200"
    volumes:
    - './tmp/vault:/vault/file'
    environment:
    - "VAULT_DEV_ROOT_TOKEN_ID=just-for-dev"
    - "VAULT_ADDR=http://127.0.0.1:8200"
    - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}}'
    cap_add:
    - IPC_LOCK
 ```
But this leads to `Error initializing Dev mode: Vault is already initialized`

 3. I tried this setup:
```yaml
services:
  vault:
    image: vault:latest
    ports:
    - "8200:8200"
    environment:
    - "VAULT_DEV_ROOT_TOKEN_ID=just-for-dev"
    - "VAULT_ADDR=http://127.0.0.1:8200"
    cap_add:
    - IPC_LOCK
 ```

But this doesn't persist state across restarts.

**Additional context**
Picking it up from #2265. It's actually a pretty valid use-case to restart the dev-environment and not have to deal with tokens, keys, internal status, sealing, ... because during development I'm not at all concerned with a secure, sealed and tamper proof environment. 
I know that sealing is an integral part of vault, but `dev` mode was introduced with the following in mind:
 
> The -dev flag just short-circuits a lot of setup to insecure defaults.
https://www.vaultproject.io/docs/concepts/dev-server

That was a great move! But it didn't take restarts of the dev-environment properly into consideration.
In my case I don't even care if the secrets are encrypted at all. But they have to be persistent across restarts. Even a docker-volume to store the unseal-key or providing the keys via env-var will do.

**Comment by ncabatoff** [comment]
Hi @MichaelSp,

This is a very reasonable feature request that I'm afraid we're going to reject, at least for now, for much the same reasons as #2265 was rejected.  I won't rule out the possibility that we may offer something like this in the future but there are no immediate plans.  Some alternatives you might consider:
* use transit unseal backed by a tiny vault server running transit in the cloud, using one of their free tiers
* use hcp vault's development tier (cheap, but not free)
* use auto-unseal backed by a cloud KMS (cheap, but not free)
* use one of the many GH projects that help automate shamir unsealing

In terms of the last bullet, I haven't tried https://github.com/omegion/vault-unseal, but it looks promising and is probably where I would start if I didn't already have scripts of my own that I like.  (My personal scripts aren't really at a point where they're ready to share, but that might happen someday too.)

**Comment by MichaelSp** [comment]
@ncabatoff Can you please describe the disadvantages of using an additional env-var like `VAULT_DEV_UNSEAL_KEY`?

I think this approach is by far the best solution compared to the proposals that you outlined.

**Comment by okamototk** [comment]
I would like to request persistent for dev mode. Primary usecase is on Laptop and Spot instance for cloud.
Then these machine/vm will be shutdown for night or unxpected timing.
I don't want initialize every time after reboot...

Please consider it.

**Comment by jameskunc** [comment]
```
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/file:/vault/file
      - ./vault/config:/vault/config
    command: vault server -config=/vault/config/config.hcl

  vault-unseal:
    image: ghcr.io/omegion/vault-unseal:latest
    depends_on:
      - vault
    entrypoint: /bin/sh
    command: >
      -c "
        echo 'Waiting 10 seconds for Vault to start...';
        sleep 10;
        vault-unseal unseal --address http://vault:8200 --shard Token1 --shard Token2 --shard Token3
      "
```
