### ISSUE TITLE
Thousands of files piling up in Vault GCP Cloud bucket

### ISSUE THREAD

**Issue by jimsnab** [hashicorp/vault#12634]
**Describe the bug**
I have a Vault cluster installed with Helm on a GKE three zone 3 node per zone cluster. Vault is unsealed but so far unused. The storage is growing with files like

gs://myproject-vault-storage/core/lock#1632413922844207
gs://myproject-vault-storage/sys/counters/requests/2021/09#1632419840300252

After 6 days there are almost 4k of these files.

**To Reproduce**
1. Create a 3x3 node cluster in GKE
2. Create GCP service account for Vault and obtain credentials in a recommended way (ex: `gcloud iam service-accounts keys create` to obtain vault_gcs_key.json) and store in the cluster as a kube secret. (See yaml below for expected key names.)
3. Mint a private tls cert and store it in the cluster as a kube secret similar to step 2
4. Create a crypto key named vault-auto-unseal-key. Refer to Hashi instructions on auto unseal.
5. Create cloud storage bucket corresponding to yaml
6. Install chart - see below
7. Manually initialize the vault - auto unseal should now work
8. After awhile, examine the cloud storage bucket and notice the steady growth of files.

**Expected behavior**
Files come and go but do not accumulate in the thousands.

**Environment**
* Kubernetes version:  GKE 1.21
* vault-helm version: 0.16

Chart values:

```yaml
global:
  tlsDisable: false

server:
  extraEnvironmentVars:
    GOOGLE_REGION: ${region}
    GOOGLE_PROJECT: "${project_id}"
    GOOGLE_CREDENTIALS: /vault/userconfig/vault-gcs/vault_gcs_key.json
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/vault-gcs/vault_gcs_key.json
    VAULT_CACERT: /etc/tls/vault-tls/intermediate-ca-cert.pem
  extraVolumes:
  - type: secret
    name: vault-gcs
    path: "/vault/userconfig"
  - type: secret
    name: vault-tls
    path: "/etc/tls"

  authDelegator:
    enabled: true

  ha:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 0
        tls_cert_file = "/etc/tls/vault-tls/vault-cert.pem"
        tls_key_file = "/etc/tls/vault-tls/vault-tls-key.pem"
        tls_client_ca_file =  "/etc/tls/vault-tls/intermediate-ca-cert.pem"
        tls_min_version = "tls12"
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "gcs" {
        bucket     = "${project_id}-vault-storage"
        ha_enabled = "true"
      }
      seal "gcpckms" {
        project     = "${project_id}"
        region      = "global"
        key_ring    = "vault-key-ring"
        crypto_key  = "vault-auto-unseal-key"
      }
```

**Additional context**
-
