### ISSUE TITLE
Vault agent: failed to read PKI CA Certificate

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault#13533]
**Describe the bug**
Get PKI CA Certificate with Vault Agent fails. 

**To Reproduce**
I'm using vault agent injector and eventual vault agent config looks like: 

```json
{
  "auto_auth": {
    "method": {
      "type": "kubernetes",
      "mount_path": "auth/kubernetes",
      "config": {
        "role": "default"
      }
    },
    "sink": [
      {
        "type": "file",
        "config": {
          "path": "/home/vault/.vault-token"
        }
      }
    ]
  },
  "exit_after_auth": false,
  "pid_file": "/home/vault/.pid",
  "vault": {
    "address": "http://vault.vault.svc:8200"
  },
  "template": [
    {
      "destination": "/vault/secrets/crt",
      "contents": "{{ secret \"pki/ca/pem\" }}\n",
      "left_delimiter": "{{",
      "right_delimiter": "}}"
    }
  ],
  "template_config": {
    "exit_on_retry_failure": true
  }
}
```

**Environment:**
vault 1.8.1

**Additional context**
I'm using vault agent injector to create vault agent config with annotation:
 ```yaml
vault.hashicorp.com/agent-inject-secret-crt: pki/ca/pem
vault.hashicorp.com/agent-inject-template-crt: |
   {{ secret "pki-kafka/ca/pem" }}
```
