### ISSUE TITLE
[UI] Can't permanently delete

### ISSUE THREAD

**Issue by Shini31** [hashicorp/vault#13584]
**Describe the bug**
I can't permanently delete a secret but I can delete the current version of the secret with the UI

**To Reproduce**
The user _test-delete- has the _test-delete_ role linked to the _test-delete_ policy
```
data:
  accessor: xyz
  creation_time: 1641480858
  creation_ttl: 3153600000
  display_name: token-test-delete
  entity_id: ""
  expire_time: "2121-12-13T14:54:18.873009818Z"
  explicit_max_ttl: 0
  id: ""
  issue_time: "2022-01-06T14:54:18.873016315Z"
  meta: null
  num_uses: 0
  orphan: false
  path: auth/token/create/test-delete
  policies:
  - default
  - test-delete
  renewable: false
  role: test-delete
  ttl: 3153598105
  type: service
lease_duration: 0
lease_id: ""
renewable: false
request_id: x-x-x
warnings: null
```

```
vault policy read test-delete
path "secret/*" {
  capabilities = ["list"]
}
path "secret/metadata" {
  capabilities = ["list", "read"]
}
path "secret/data/test/*" {
  capabilities = ["create", "read", "update", "delete"]
}
```

When I click on _delete_, the popup comes back to _Permanently delete_ action

![permanently-delete](https://user-images.githubusercontent.com/333820/148404338-bb4a0c03-1649-4d2d-b070-4136ab89efea.png)
![permanently-delete-02](https://user-images.githubusercontent.com/333820/148404349-3df2ebec-0be3-499d-866e-0823a6392f7a.png)

**Expected behavior**
I can permanently delete a secret with the UI

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2 on 3 nodes with HA by Consul
* Vault CLI Version (retrieve with `vault version`): Vault v1.9.2 (f4c6d873e2767c0d6853b5d9ffc77b0d297bfbdf)
* Server Operating System/Architecture: Ubuntu 16.04

Vault server configuration file(s):

```hcl
ui = true

listener "tcp" {
    address = "foo.bar:8200"
    cluster_address = "foo.bar8201"
    tls_disable = 0
    tls_cert_file = "/usr/local/share/ca-certificates/foo.bar.fullchain.crt"
    tls_key_file = "/etc/ssl/private/foo.barkey"
    telemetry {
      unauthenticated_metrics_access = true
    }
}

storage "consul" {
    address = "localhost:8500"
    scheme = "http"
    path    = "vault/"
    token   = "x-x-x-x"
    service = "vault"
    service_address = ""
    service_tags = "vault"
}

api_addr = "https://foo.bar:8200"
cluster_addr = "https://foo.bar:8201"

log_format = "json"
log_level = "warn"

telemetry {
  prometheus_retention_time = "30s",
  disable_hostname = true
}

```

**Additional context**
