### ISSUE TITLE
Deleted secrets are restored in Kubernetes on scale cmd

### ISSUE THREAD

**Issue by stremovsky** [hashicorp/vault#13676]
**Describe the bug**

After starting the application server in the Kubernetes container, I want to delete the secret files to harden the container.

After deleting the secret files, it turned out that the secret file is restored when scaling up or down.
```kubectl scale --replicas=3 deployment website```

**To Reproduce**
1. I followed this official tutorial to setup Vault and Vault Agent. I am using kubernetes in AWS:
https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar
2. Create deployment-website.yaml file
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "internal/data/database/config" -}}
          postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard
          {{- end -}}
      labels:
        app: website
    spec:
      # This service account does not have permission to request the secrets.
      serviceAccountName: internal-app
      containers:
        - name: website
          image: jweissig/app:0.0.1
```
3. Deploy this file in kubernetes. Run ```kubectl apply deployment-website.yaml```
3. Run ```kubectl get pods```
```NAME                                    READY   STATUS    RESTARTS   AGE
vault-0                                 1/1     Running   0          6h11m
vault-agent-injector-7d48667d44-b86fg   1/1     Running   0          6h11m
website-844dbf6fcb-v9h2h                2/2     Running   0          32m
```
4. Check that secret file exists in website pod:
```
kubectl exec website-844dbf6fcb-v9h2h -- ls /vault/secrets/database-config.txt
Defaulted container "website" out of: website, vault-agent, vault-agent-init (init)
/vault/secrets/database-config.txt
```
5. Delete secret file inside container and check that file no longer exists.
```
kubectl exec website-844dbf6fcb-v9h2h -- rm /vault/secrets/database-config.txt

kubectl exec website-844dbf6fcb-v9h2h -- ls /vault/secrets/database-config.txt
Defaulted container "website" out of: website, vault-agent, vault-agent-init (init)
ls: /vault/secrets/database-config.txt: No such file or directory
command terminated with exit code 1
```
6. You need to run scale up or scale down deployment several times.

I am using the following command: ***kubectl scale --replicas=3 deployment website***

After each scale command check if secret file is restored in the same website pod.
Check that secret files was created again!
```
kubectl exec website-844dbf6fcb-v9h2h -- ls /vault/secrets/database-config.txt
Defaulted container "website" out of: website, vault-agent, vault-agent-init (init)
/vault/secrets/database-config.txt
```

**Expected behavior**

**The deleted secret files should never be restored in the running POD.**

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.9.0
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):
default

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**
