### ISSUE TITLE
The `consul` user does not have write access to /consul/data in the offical docker image. 

### ISSUE THREAD

**Issue by fxdgear** [hashicorp/vault#1382]
The GH repo https://github.com/hashicorp/docker-consul does not support issues, so filing here. 

When running docker-compose with the offical docker image I get the following error 
```
Error starting agent: Failed to start Consul server: Failed to start Raft: mkdir /consul/data/raft: permission denied
```
docker-compose.yml
```yaml
consul:
  image: consul:latest
  command: agent -server -config-file /consul/config/consul.json -ui-dir /opt/consul/ui
  volumes:
    - "./services/vault/consul/assets/conf.d:/consul/config:ro"
    - "./services/vault/consul/data:/consul/data:rw"
```
