### ISSUE TITLE
RabbitMQ engine produces multiple users for one service call

### ISSUE THREAD

**Issue by Mercanuis** [hashicorp/vault#13857]
**Describe the bug**

Apologies but I am not sure if this is a question or an actual bug, so to be on the safe side I wanted to bring it up here. 

I have been learning Vault Agent and its use with [K8s](https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar?in=vault/kubernetes) with [RabbitMQ engine](https://www.vaultproject.io/docs/secrets/rabbitmq) and [CSI](https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver) on my minikube environment. When I run via the Vault Agent, I am noticing that for every one service I deploy to my minikube, there are two users generated on the Rabbit Cluster. The service is able to log in, but I am curious and confused as to why there are two users being deployed instead of the one. Using CSI, one user is generated which is expected. 

**To Reproduce**

1. Set up minikube environment with the Vault Helm Chart
```
helm install vault hashicorp/vault \
    --set "server.dev.enabled=true" \
    --set "debug=true" \
    --set "injector.logLevel=debug" \
    --set "server.logLevel=debug" \
    --set "csi.enabled=true"
```

2. Set up the Vault secret for the Rabbit User. This was done via a shell by k9s, but a normal `kubectl exec` should work too
```
# Enable the key-value secret engine in the pod
vault secrets enable -path=internal kv-v2

# Generate the secret that will be the admin password for Rabbit
vault kv put internal/rabbit/user username="rabbit" password="rabbit"

# Verify
vault kv get internal/rabbit/user

# Enable K8s auth engine
vault auth enable kubernetes

# Configure the authentication method for local minikube
vault write auth/kubernetes/config \
      kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" \
      token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
      kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
      issuer="https://kubernetes.default.svc.cluster.local"

# Generate the Policy for Read access to the Vault per the given path
vault policy write rabbitmq - <<EOF
path "internal/data/rabbit/user" {
  capabilities = ["read"]
}
EOF  

# Write K8s auth role
vault write auth/kubernetes/role/rabbitmq-cluster-server \
      bound_service_account_names=rabbitmq-cluster-server \
      bound_service_account_namespaces=iot \
      policies=rabbitmq \
      ttl=24h
```

3.  Deploy the RabbitMq Cluster
Sample Deployment YAML
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: namespaceA
spec:
  replicas: 1
  image: rabbitmq:3.9.12-management
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  # Ref: https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/vault-default-user/rabbitmq.yaml
  secretBackend:
    vault:
      role: rabbitmq-cluster-server # The role is the same that is set up by the cluster deployment per the metadata.name field, so if that changes you need to change this too
      annotations:
        vault.hashicorp.com/template-static-secret-render-interval: "15s"
      defaultUserPath: internal/data/rabbit/user # Relates to the path in the Vault
      defaultUserUpdaterImage: "" # This is used to disable the sidecar that lets Rabbit auto-update the password for you
  override:
    statefulSet:
      spec:
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: persistence
              namespace: namespaceA
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              volumeMode: Filesystem
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_management
    additionalConfig: |
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
```

4. Generate the RabbitMQ Policy
```
vault secrets enable rabbitmq

# Set up the admin connection for Vault to talk to Rabbit with
vault write rabbitmq/config/connection \
    connection_uri="http://rabbit@rabbitmq-cluster-server-0.rabbitmq-cluster-nodes.namespaceA.svc.cluster.local:15672" \
    username="rabbit" \
    password="rabbit"

# Set up the role definition for a user
vault write rabbitmq/roles/example-role \
    vhosts='{"a":{"write": ".*", "read": ".*"}, "/":{"write": ".*", "read": ".*"}}' \
    tags="management"

# Generate policy 
vault policy write rabbitmq-role - <<EOF
path "rabbitmq/creds/example-role" {
    capabilities = ["read"]
}
EOF

# Bind policy to a role
vault write auth/kubernetes/role/subscriber \
    bound_service_account_names=example-service \
    bound_service_account_namespaces=namespaceA \
    policies=rabbitmq-role \
    ttl=24h

```

5. Deploy the service per the Vault Injection
```
apiVersion: apps/v1
kind:       Deployment
metadata:
  name: {{ include "subscriber.fullname" . }}
  labels:
    {{- include "subscriber.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "subscriber.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'subscriber'
        vault.hashicorp.com/agent-inject-secret-subscriber-parameters: 'rabbitmq/creds/rabbitmq-role'
      labels:
        {{- include "subscriber.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "subscriber.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name:          http
              containerPort: 80
              protocol:      TCP
            - name:          mqtt
              containerPort: 1883
              protocol:      TCP
          env:
            {{ range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          resources:
            limits:
              cpu:    200m
              memory: 200Mi
            requests:
              cpu:    200m
              memory: 200Mi
```

**Expected behavior**
Upon a successful startup, the service is connected to the Rabbit Cluster, and there is a **single** new user on the Cluster per the policy

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.9.2 (f4c6d873e2767c0d6853b5d9ffc77b0d297bfbdf)
* Server Operating System/Architecture: macOS (M1) using Minikube with Docker as backing VM driver

Vault server configuration file(s): None

**Additional context**
The Vault is making a correct credential that the service can use, this behavior I just don't know where to look or why its occurring.
