### ISSUE TITLE
Getting 403 error after restarting vault

### ISSUE THREAD

**Issue by thulasidassrinivasan** [hashicorp/vault#13873]
**Describe the bug**
Getting 403 error after restarting vault in aks

**To Reproduce**
1. Restart the vault pod one by one. 
2. Once the master vault pod restarts, the tfc hosted agents we have can no longer connect. We are getting 403 error

**Expected behavior**
No error and agents are able to connect

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-in-cert
  namespace: vault
spec:
  secretName: vault-innovasjonnorge-no
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
  - vault.innovasjonnorge.no
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-allow-ingress
  namespace: vault
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vault
      component: server
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: vault
spec:
  url: https://helm.releases.hashicorp.com
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.14.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  values:
    server:
      # extraVolumes:
      #   - type: secret
      #     name: seal-secret-config
      volumes:
        - name: seal-secret-config
          secret:
            secretName: seal-secret-config
      volumeMounts:
        - mountPath: /vault/userconfig/seal-secret-config/
          name: seal-secret-config
          readOnly: true
      extraArgs: "-config /vault/userconfig/seal-secret-config/seal-secret.hcl"
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
      ingress:
        enabled: true
        annotations:
          appgw.ingress.kubernetes.io/ssl-redirect: "true"
          kubernetes.io/ingress.class: azure/application-gateway
        hosts:
          - host: vault.innovasjonnorge.no
        tls:
          - secretName: vault-innovasjonnorge-no
            hosts:
              - vault.innovasjonnorge.no
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 300m
```

```hcl
---
apiVersion: v1
kind: Namespace
metadata:
  name: tfc-agent
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: innovationnorway
  namespace: tfc-agent
spec:
  url: https://innovationnorway.github.io/platform-kubernetes-config/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tfc-agent
  namespace: tfc-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: tfc-agent
      version: "0.8.0"
      sourceRef:
        kind: HelmRepository
        name: innovationnorway
  values:
    replicaCount: 4
    serviceAccount:
      create: true
    terraformCloudSecrets:
      enabled: false
    command:
      enabled: true
      cmd:
        - /bin/bash
        - -c
      args:
        - "source /vault/secrets/config && /home/tfc-agent/bin/tfc-agent"
    env:
    - name: VAULT_ADDR
      value: https://vault.innovasjonnorge.no
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'tfc-agent'
      vault.hashicorp.com/agent-inject-secret-config: 'tfc-config/data/agent'
      # Environment variable export template
      vault.hashicorp.com/agent-inject-template-config: |
        {{- with secret "tfc-config/data/agent" -}}
          export TFC_AGENT_NAME="{{ .Data.data.name }}"
          export TFC_AGENT_TOKEN="{{ .Data.data.token }}"
        {{- end }}
---
```

**Additional context**
How to overcome this issue please advise.
