### ISSUE TITLE
servicemonitor for vault

### ISSUE THREAD

**Issue by mohan-nagandlla** [hashicorp/vault#13978]
HI team
Prometheus is running under operator CRD we can able to add the target by two ways that is servicemonitor or podmontior. 
But for adding the target we need to pass the credentials files which is not support by the CRDS do we have any other way to add the target to the proemtheus by using the serviecaccount kubernetes authentication method? 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    purpose: prometheus-prometheus
  name: vault
  namespace: vaultnew
spec:
  endpoints:
  - path: /v1/sys/metrics
    params:
      format: ['prometheus']
    scheme: http
    targetPort: 8200
    tlsConfig:
      insecureSkipVerify: true
    authorization:
      credentials:
        key: token-prom
        name: vault-prom
  namespaceSelector:
    matchNames:
    - vaultnew
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
```
![image](https://user-images.githubusercontent.com/52690110/153254235-a398982a-2246-43e1-95db-9b5cab0a2c0d.png)
