### ISSUE TITLE
Access an input file from vault template injector

### ISSUE THREAD

**Issue by Mouad-B** [hashicorp/vault#14613]
Vault injector allow us to create our own template and editing it with some secrets from vault or import an existing secret using extra-secret and using it as is. What if we want to import a file like we do with extra-secret and make that file accessible to to inject-template-SECRET so we can for example do some replacements?

Something like this could be useful especially when we end up with big configuration files which may be split into multiple sub-configs:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-app
spec:
  ...
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-extra-secret: my-configs
        vault.hashicorp.com/secret-volume-path-my-config: "/my-path/etc"
        vault.hashicorp.com/agent-inject-file-my-config: "my-app.conf"
        vault.hashicorp.com/agent-inject-secret-my-config: secret/data/my-app/config
        vault.hashicorp.com/agent-inject-template-my-config: |
          {{ .Files.Get "custom/init.conf" }}
          {{- $file := .Files }}
          {{- with secret "secret/data/my-app/config" -}}
          # ...
          # ... replacing variables in the configuration present in custom/build.conf
          # ...
          {{- end }}
```

with `my-configs` secret generated for example with `init.conf`, `build.conf`... etc

This is just a suggestion.. Importing an editable configuration stills the main purpose here.
