### ISSUE TITLE
JWT/OIDC config for Kubernetes fails with audience claim does not match any expected audience

### ISSUE THREAD

**Issue by Jasper-Ben** [hashicorp/vault#16033]
**Describe the bug**
Trying to use JWT for authenticating the Kubernetes vault-injector against vault results in the following error:

```
│ vault-agent-init 2022-06-17T10:09:39.873Z [INFO]  auth.handler: authenticating                                                                                                                                                             │
│ vault-agent-init 2022-06-17T10:09:39.873Z [ERROR] auth.jwt: error removing jwt file: error="remove /var/run/secrets/kubernetes.io/serviceaccount/token: read-only file system"                                                             │
│ vault-agent-init 2022-06-17T10:09:39.925Z [ERROR] auth.handler: error authenticating:                                                                                                                                                      │
│ vault-agent-init   error=                                                                                                                                                                                                                  │
│ vault-agent-init   | Error making API request.                                                                                                                                                                                             │
│ vault-agent-init   |                                                                                                                                                                                                                       │
│ vault-agent-init   | URL: PUT https://<vault_uri>/v1/auth/<auth_path>/login                                                                                                                        │
│ vault-agent-init   | Code: 400. Errors:                                                                                                                                                                                                    │
│ vault-agent-init   |                                                                                                                                                                                                                       │
│ vault-agent-init   | * error validating token: invalid audience (aud) claim: audience claim does not match any expected audience                                                                                                           │
│ vault-agent-init    backoff=4m26s         
``` 

**To Reproduce**
Follow the documentation on setting up JWT/OIDC for Kubernetes with external vault cluster as described here:
- https://www.vaultproject.io/docs/auth/jwt/oidc_providers#kubernetes
- https://www.vaultproject.io/docs/auth/jwt#redirect-uris

**Expected behavior**
vault agent from the k8s injector should be able to authenticate against vault.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.10.3 (helm chart version 0.20.1)
* Vault CLI Version (retrieve with `vault version`): -
* Server Operating System/Architecture: Separate Vault helm installations for vault server and vault injector running on AWS EKS
* Terraform Vault Provider: 3.6.0

Vault server configuration file(s) (user supplied helm values):

```yaml
global:
  enabled: true
  tlsDisable: false
injector:
  enabled: false
server:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/taints
            operator: In
            values:
            - vault
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - vault
        topologyKey: topology.kubernetes.io/zone
  dataStorage:
    storageClass: efs-persistent
  extraEnvironmentArgs:
    VAULT_AWSKMS_SEAL_KEY_ID: <ID>
    VAULT_SEAL_TYPE: awskms
  ha:
    enabled: true
    raft:
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_ca_cert_file = "/vault/userconfig/certs/ca.crt"
          tls_cert_file = "/vault/userconfig/certs/tls.crt"
          tls_key_file = "/vault/userconfig/certs/tls.key"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
          leader_api_addr = "https://vault-0.vault-internal:8200"
          leader_ca_cert_file = "/vault/userconfig/certs/ca.crt"
          leader_client_cert_file = "/vault/userconfig/certs/tls.crt"
          leader_client_key_file = "/vault/userconfig/certs/tls.key"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/certs/ca.crt"
            leader_client_cert_file = "/vault/userconfig/certs/tls.crt"
            leader_client_key_file = "/vault/userconfig/certs/tls.key"
          }
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/certs/ca.crt"
            leader_client_cert_file = "/vault/userconfig/certs/tls.crt"
            leader_client_key_file = "/vault/userconfig/certs/tls.key"
          }
          autopilot {
            cleanup_dead_servers = "true"
            last_contact_threshold = "200ms"
            last_contact_failure_threshold = "10m"
            max_trailing_logs = 250000
            min_quorum = 3
            server_stabilization_time = "10s"
          }
        }

        seal "awskms" {
            region      = "eu-central-1"
            kms_key_id = <key_id>
            endpoint   = "https://kms.eu-central-1.amazonaws.com"
        }

        service_registration "kubernetes" {}
      enabled: true
    replicas: 3
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: <role_arn>
    name: vault
  tolerations:
  - effect: NoSchedule
    key: vault
    operator: Exists
  volumeMounts:
  - mountPath: /vault/userconfig/certs
    name: vault-certificate
    readOnly: true
  volumes:
  - name: vault-certificate
    secret:
      secretName: vault-certificate
```

Vault injector configuration file(s) (user supplied helm values):

```yaml
global:
  enabled: true
injector:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: node.kubernetes.io/lifecycle
            operator: In
            values:
            - spot
        weight: 1
  annotations:
    vault.hashicorp.com/auth-type: jwt
  authPath: auth/jwt
  enabled: true
  externalVaultAddr: https://<vault_uri>
  extraEnvironmentVars:
    AGENT_INJECT_VAULT_AUTH_PATH: auth/jwt
  metrics:
    enabled: true
  replicas: 3
```

vault jwt backend config (terraform):

```
resource "vault_jwt_auth_backend" "oidc_auth_backend" {
    description         = "${var.mount_path} vault OIDC auth backend"
    path                = var.mount_path
    type                = "jwt"
    oidc_discovery_url  = var.oidc_discovery_url
    default_role        = "${var.mount_path}-role"
}

resource "vault_jwt_auth_backend_role" "oidc_auth_backend_role" {
  backend = vault_jwt_auth_backend.oidc_auth_backend.path
  role_name = "${var.mount_path}-role"
  bound_audiences = [var.oidc_discovery_url]
  role_type = "jwt"
  user_claim = "sub"
  bound_subject = "system:serviceaccount:${var.serviceaccount_namespace}:${var.serviceaccount_name}"
  token_policies = var.token_policies
  token_ttl = 3600
  allowed_redirect_uris = [
    "${var.vault_address}/ui/vault/auth/${var.mount_path}/oidc/callback",
    "http://localhost:8250/oidc/callback"
  ]
}
```

Kubernetes testpod trying to use vault injector (k8s manifest yaml):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: <namespace>
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/auth-type: "jwt"
    vault.hashicorp.com/auth-config-path: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    vault.hashicorp.com/auth-path: <auth_path>
    vault.hashicorp.com/auth-config-role: <auth_role>
    vault.hashicorp.com/agent-inject-secret-cert.pem: "<secret_path>/cert/<cert_serial>/raw/pem"
spec:
  serviceAccountName: <service_account_name>
  containers:
  - name: nginx
```
