### ISSUE TITLE
k8s auth failed - service account unauthorized

### ISSUE THREAD

**Issue by evarganov** [hashicorp/vault#16123]
When trying to authenticate using the cs method, we get the following error
[ERROR] auth.kubernetes.auth_kubernetes_*: login unauthorized due to: lookup failed: [invalid bearer token, Token has been invalidated]

Using following command to login:
`curl  --request POST  --data '{"jwt": "TOKEN_REVIEW_JWT", "role": "k8s-cluster_role"}'  https://vault/v1/auth/k8s-cluster/login`

```
$vault status

Key                    Value
---                    -----
Seal Type              shamir
Initialized            true
Sealed                 false
Total Shares           5
Threshold              3
Version                1.9.7
Storage Type           consul
Cluster Name           vault-cluster
Cluster ID             -
HA Enabled             true
HA Cluster             https://host:port
HA Mode                active
Active Node Address    https://host:port
```

Resources in k8s creating with following commands:
```
kubectl create namespace vault-infra

cat <<EOF | kubectl create -f -
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault-infra
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: vault-infra
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: vault-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: vault-infra
EOF


TOKEN_REVIEW_JWT=$(kubectl get secret -n vault-infra vault-auth -o go-template='{{ .data.token }}' | base64 --decode)
KUBE_CA_CERT=$(kubectl config view -n vault-infra --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 --decode)
KUBE_HOST=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.server}')
```

Vault auth method configuring by the following commands:
```
vault auth enable -path=k8s-cluster kubernetes

vault write auth/k8s-cluster/config  kubernetes_host=$KUBE_HOST jwt=$TOKEN_REVIEW_JWT kubernetes_ca_cert=$KUBE_CA_CERT disable_local_ca_jwt=true disable_iss_validation=true

vault write auth/k8s-cluster/role/k8s-cluster_role \
    bound_service_account_names=vault-auth \
    bound_service_account_namespaces=* \
    policies=default \
    ttl=1h
```

Recreating the SA jwt has no effect.

We have more than one clusters connected to this Vault install, but there is a problem with this cluster.
