### ISSUE TITLE
Vault with Integrated Storage: nodes unable to join the cluster after being stopped

### ISSUE THREAD

**Issue by aqua777** [hashicorp/vault#17014]
**Vault with Integrated Storage: nodes unable to join the cluster after being stopped**
We are testing Integrated Storage for Vault server. We setup test cluster using `docker-compose` with 5 containers connected by Docker network . We configured the cluster to removed dead server after 10s timeout and we shut down one of the nodes. The affected node gets ejected from the cluster as expected. However, when we start it and unseal it, it doesn't join the cluster.

The only way we were able to attach affected node to the cluster was by stopping Vault server, removing directory containing Vault files and starting Vault server again. In this case, ufter unsealing the node joins the cluster.

**To Reproduce**
1. Setup test cluster with 5 servers or containers running Vault
2. Start 1st Vault server, initiate it, note the root token and unseal key
3. Unseal 1st Vault server
4. On each of remaining 4 nodes or containers start and unseal Vault server
5. Run `vault operator raft list-peers` to confirm 5 nodes in cluster, the leader and voter status of all nodes
6. Configure Raft Autopilot:
   ```
   vault operator raft autopilot set-config \
    -dead-server-last-contact-threshold=10 \
    -server-stabilization-time=30 \
    -cleanup-dead-servers=true \
    -min-quorum=3
    ```
7. Select one of the Vault servers and stop it, wait until it is removed from list of Raft peers
8. Start previously stopped Vault server and unseal it.
9. The server does not join the cluster
10. Run command:
   ```
   vault operator raft join http://<leader_ip>:8200
   ```
   and see the output:
   ```
   Key       Value
   ---       -----
   Joined    true
   ```
   Despite command claiming success the affected node still doesn't join the cluster
 11. Stop Vault server, remove all files and subdirectories from `/var/lib/vault/data/test`
 12. Start Vault server again and unseal it
 13. Run `vault operator raft list-peers` and see the affected node now being part of the cluster

**Expected behavior**
We expected the restarted server to join cluster back after stabilization period of 30 seconds per Raft Autopilot configuration command in p.6

Are we missing something here?

**Environment:**
* Vault Server Version 1.11.3
* Vault CLI Version 1.11.3
* Server Operating System/Architecture:
  - 5 servers with Vault v1.11.3 or 5 containers started with Docker Compose based on public `vault:1.11.3` image
  - physical or virtual network to connect servers or containers
  - configuration as described below

Vault server configuration file(s):

```hcl
api_addr         = "http://192.168.211.21:8200"
cluster_addr     = "http://192.168.211.21:8201"
disable_mlock    = false
plugin_directory = "/plugins"

listener "tcp" {
  address           = "0.0.0.0:8200"
  cluster_address   = "0.0.0.0:8201"
  tls_disable       = 1

  telemetry {
    unauthenticated_metrics_access = true
  }
}

storage "raft" {
  path    = "/var/lib/vault/data/test"
  node_id = "vault1"

  retry_join {
    leader_api_addr = "http://vault1:8200"
  }
  retry_join {
    leader_api_addr = "http://vault2:8200"
  }
  retry_join {
    leader_api_addr = "http://vault3:8200"
  }
  retry_join {
    leader_api_addr = "http://vaulr4:8200"
  }
  retry_join {
    leader_api_addr = "http://vault5:8200"
  }
}

telemetry {
  prometheus_retention_time = "1h"
  disable_hostname          = true
}
```

**Comment by aqua777** [comment]
Docker Compose config file:
```yaml
version: '3.8'
services:
  vault1:
    image: vault:1.11.3
    container_name: vault1
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 500m
    hostname: vault1
    networks:
      inner-network:
        ipv4_address: 192.168.211.21
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    cap_add:
      - IPC_LOCK
    privileged: true
    environment:
      - "VAULT_ADDR=http://vault1:8200"
      - "PS1=[\\u@\\h \\W]# "

  vault2:
    image: vault:1.11.3
    container_name: vault2
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 500m
    hostname: vault2
    networks:
      inner-network:
        ipv4_address: 192.168.211.22
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    cap_add:
      - IPC_LOCK
    privileged: true
    environment:
      - "VAULT_ADDR=http://vault1:8200"
      - "PS1=[\\u@\\h \\W]# "

  vault3:
    image: vault:1.11.3
    container_name: vault3
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 500m
    hostname: vault3
    networks:
      inner-network:
        ipv4_address: 192.168.211.23
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    cap_add:
      - IPC_LOCK
    privileged: true
    environment:
      - "VAULT_ADDR=http://vault1:8200"
      - "PS1=[\\u@\\h \\W]# "

  vault4:
    image: vault:1.11.3
    container_name: vault4
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 500m
    hostname: vault4
    networks:
      inner-network:
        ipv4_address: 192.168.211.24
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    cap_add:
      - IPC_LOCK
    privileged: true
    environment:
      - "VAULT_ADDR=http://vault1:8200"
      - "PS1=[\\u@\\h \\W]# "

  vault5:
    image: vault:1.11.3
    container_name: vault5
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 500m
    hostname: vault5
    networks:
      inner-network:
        ipv4_address: 192.168.211.25
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    cap_add:
      - IPC_LOCK
    privileged: true
    environment:
      - "VAULT_ADDR=http://vault1:8200"
      - "PS1=[\\u@\\h \\W]# "

networks:
  inner-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.211.0/24
```
