### ISSUE TITLE
GCP KMS Autounseal Error bug

### ISSUE THREAD

**Issue by KosShutenko** [hashicorp/vault#17850]
**Describe the bug**
I have installed Vault clusters from chart v 0.22.0 into few Kubernetes clusters v1.23.8-gke.1900 with auto-unseal via GCP KMS.
After upgrade Vault chart to version 0.22.1 I've got error:
```
Error parsing Seal configuration: error checking key existence: rpc error: code = PermissionDenied desc = Permission 'cloudkms.cryptoKeys.get' denied on resource 'projects/MY_PROJECT_NAME/locations/europe-west2/keyRings/vault-unseal-ring/cryptoKeys/vault-unseal-key' (or it may not exist).
```
After downgrade to 0.22.0 issue was solved. But now I cannot have up-to-date Vault clusters.

**To Reproduce**
1. Install Vault cluster from chart v 0.22.0
2. Configure auto-unseal via GCP KMS
3. Upgrade chart version from 0.22.0 to 0.22.1 and wait until statefulset will be upgraded.
4. Remove one pod to recreate it and check logs.

**Expected behavior**
All pods should be upgraded and started from new version and with auto-unseal via GCP KMS.

**Comment by jawnsy** [comment]
I ran into the same problem when upgrading Vault using the Helm chart, from version 0.21.0 to 0.23.0 of the chart. The solution is to provide the [Cloud KMS Viewer role](https://cloud.google.com/kms/docs/reference/permissions-and-roles#cloudkms.viewer) (in addition to Cloud KMS CryptoKey Encrypter/Decrypter) to the service account.

I suspect that the issue is that a check was added somewhere to check for the key existence, whereas Vault previously just tried to use the key.

You can replicate Vault's behavior by creating a pod using the same service account using the `google/cloud-sdk` image, and then running:

```
# gcloud kms keys describe ghi --keyring=def --location=global --project=abc
ERROR: (gcloud.kms.keys.describe) PERMISSION_DENIED: Permission 'cloudkms.cryptoKeys.get' denied on resource 'projects/abc/locations/global/keyRings/def/cryptoKeys/ghi' (or it may not exist).
```

Once you grant the KMS viewer role, you should see output like this:

```
# gcloud kms keys describe ghi --keyring=def --location=global --project=abc
createTime: '2019-12-10T20:42:09.838170389Z'
destroyScheduledDuration: 86400s
name: projects/abc/locations/global/keyRings/def/cryptoKeys/ghi
nextRotationTime: '2022-12-04T04:13:44.120438Z'
primary:
  algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
  createTime: '2022-12-03T00:27:04.120438038Z'
  generateTime: '2022-12-03T00:27:04.120438038Z'
  name: projects/abc/locations/global/keyRings/def/cryptoKeys/ghi/cryptoKeyVersions/3
  protectionLevel: SOFTWARE
  state: ENABLED
purpose: ENCRYPT_DECRYPT
rotationPeriod: 100000s
versionTemplate:
  algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
  protectionLevel: SOFTWARE
```
