### ISSUE TITLE
Re-keying vault prints no display keys and an incorrect amount of key shares and key threshold

### ISSUE THREAD

**Issue by thatsnotamuffin** [hashicorp/vault#18574]
**Describe the bug**
When re-keying vault no unseal keys are displayed and an incorrect amount of key shares and key threshold is displayed

**To Reproduce**
1. Run `vault operator rekey -init -key-shares=5 -key-threshold=3`
2. Run `vault operator rekey -nonce="xxx-xxx-xxx-xxx-xxx"`
3. Run that x amount of times to meet the previous key threshold to rekey
4. Output of "Vault rekeyed with 1 key shares and a key threshold of 1. Please securely distribute the key shares printed above. When Vault is re-sealed, restarted, or stopped, you must supply at least 1 of these keys to unseal it before it can start servicing requests." and no unseal key is printed as well as incorrect amount of key shares and key threshold is displayed

**Expected behavior**
5 key shares should be created with a threshold of 3 and the unseal keys should be printed to the screen

**Environment:**
* Vault Server Version: 1.9.3
* Vault CLI Version: Vault v1.9.3 (7dbdd57243a0d8d9d9e07cd01eb657369f8e1b8a)
* Server Operating System/Architecture: Kubernetes using AWS EKS

Vault server configuration file(s):

```yaml
---
global:
  enabled: true
  imagePullSecrets: []
  tlsDisable: true
  openshift: false
  psp:
    enable: false
    annotations: |
      seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
      apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
      seccomp.security.alpha.kubernetes.io/defaultProfileName:  runtime/default
      apparmor.security.beta.kubernetes.io/defaultProfileName:  runtime/default
injector:
  enabled: true

  replicas: 1

  port: 8080

  leaderElector:
    enabled: true

  metrics:
    enabled: false

  externalVaultAddr: ""

  image:
    repository: "hashicorp/vault-k8s"
    tag: "0.14.2"
    pullPolicy: IfNotPresent

  agentImage:
    repository: "hashicorp/vault"
    tag: "1.9.3"

  agentDefaults:

    cpuLimit: "500m"
    cpuRequest: "250m"
    memLimit: "128Mi"
    memRequest: "64Mi"

    template: "map"

    templateConfig:
      exitOnRetryFailure: true
      staticSecretRenderInterval: ""

  authPath: "auth/kubernetes"

  logLevel: "info"

  logFormat: "standard"

  revokeOnShutdown: false

  webhook:

    failurePolicy: Ignore

    matchPolicy: Exact

    timeoutSeconds: 30

    namespaceSelector: {}

    objectSelector: {}

    annotations: {}

  failurePolicy: Ignore

  namespaceSelector: {}

  objectSelector: {}

  webhookAnnotations: {}

  certs:
    secretName: null

    caBundle: ""

    certName: tls.crt
    keyName: tls.key

  resources: {}

  extraEnvironmentVars: {}

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}-agent-injector
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: webhook
          topologyKey: kubernetes.io/hostname

  tolerations: []

  nodeSelector: {}

  priorityClassName: ""

  annotations: {}

  extraLabels: {}

  hostNetwork: false

  service:
    annotations: {}

  podDisruptionBudget: {}

  strategy: {}

server:
  enabled: true

  enterpriseLicense:
    secretName: ""
    secretKey: "license"

  image:
    repository: "hashicorp/vault"
    tag: "1.9.3"
    pullPolicy: IfNotPresent

  updateStrategyType: "OnDelete"
  logLevel: ""
  logFormat: ""
  resources: {}

  ingress:
    enabled: false
    labels: {}
    annotations: {}
    ingressClassName: ""
    pathType: Prefix
    activeService: true
    hosts:
      - host: chart-example.local
        paths: []
    extraPaths: []
    tls: []

  route:
    enabled: false
    activeService: true
    labels: {}
    annotations: {}
    host: chart-example.local
    tls:
      termination: passthrough

  authDelegator:
    enabled: true
  extraInitContainers: null
  extraContainers: null
  shareProcessNamespace: false
  extraArgs: ""

  readinessProbe:
    enabled: true
    failureThreshold: 2
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3

  livenessProbe:
    enabled: false
    path: "/v1/sys/health?standbyok=true"
    failureThreshold: 2
    initialDelaySeconds: 60
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3

  terminationGracePeriodSeconds: 10
  preStopSleepSeconds: 5
  postStart: []
  extraEnvironmentVars: {}

  extraSecretEnvironmentVars:
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: aws-vault-creds
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: AWS_ACCESS_KEY_ID
      secretName: aws-vault-creds
      secretKey: AWS_ACCESS_KEY_ID

  extraVolumes: []
  volumes: null
  volumeMounts: null
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
  tolerations: []
  nodeSelector: {}
  networkPolicy:
    enabled: false
    egress: []
  priorityClassName: ""
  extraLabels: {}
  annotations: {}

  service:
    enabled: true
    publishNotReadyAddresses: true
    externalTrafficPolicy: Cluster
    port: 8200
    targetPort: 8200
    annotations: {}

  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/data"
    storageClass: null
    accessMode: ReadWriteOnce
    annotations: {}

  auditStorage:
    enabled: false
    size: 10Gi
    mountPath: "/vault/audit"
    storageClass: null
    accessMode: ReadWriteOnce
    annotations: {}

  dev:
    enabled: false
    devRootToken: "root"

  standalone:
    enabled: "-"
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

  ha:
    enabled: true
    replicas: 3
    apiAddr: null

    raft:
      enabled: false
      setNodeId: false
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }
        service_registration "kubernetes" {}

    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "dynamodb" {
        ha_enabled = "true"
        region = "us-east-2"
        table = "dynamodb-table"
        read_capacity = 15
        write_capacity = 10
      }
      seal "awskms" {
        region = "us-east-2"
        kms_key_id = "xxx-xxx-xxx-xxx-xxx"
      }
      service_registration "kubernetes" {}

    disruptionBudget:
      enabled: true
      maxUnavailable: null
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  statefulSet:
    annotations: {}

# Vault UI
ui:
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 443
  targetPort: 8200
  externalTrafficPolicy: Cluster
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:xxx:certificate/xxx
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    external-dns.alpha.kubernetes.io/hostname: my.url.com
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "35"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name=vault-lb

csi:
  enabled: false
  image:
    repository: "hashicorp/vault-csi-provider"
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  volumes: null
  volumeMounts: null
  resources: {}
  daemonSet:
    updateStrategy:
      type: RollingUpdate
      maxUnavailable: ""
    annotations: {}
    providersDir: "/etc/kubernetes/secrets-store-csi-providers"
    kubeletRootDir: "/var/lib/kubelet"
    extraLabels: {}
  pod:
    annotations: {}
    tolerations: []
    extraLabels: {}
  priorityClassName: ""
  serviceAccount:
    annotations: {}
    extraLabels: {}

  readinessProbe:
    failureThreshold: 2
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
    
  livenessProbe:
    failureThreshold: 2
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  debug: false
```
