### ISSUE TITLE
We have many tls issues since upgrade vault helm chart "vault-0.22.1." for vault 1.12.0

### ISSUE THREAD

**Issue by Mais316** [hashicorp/vault#18736]
We hit same issue here https://github.com/hashicorp/vault/issues/10395 and we are convinced that this is still a non fixed bug.

Vault is down with leader election not every one but at some at least we are down on daily bases
```
"2023-01-17T18:05:54.354Z [DEBUG] core.cluster-listener: error handshaking cluster connection: error=\"unsupported protocol\"\n"

"2023-01-17T15:38:41.964Z [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[\"req_fw_sb-act_v1\"]\n"
```

We disabled tls as well.

```yaml
global:
  tlsDisable: true

####################

server:
  enabled: true
  
  image:
    repository: "hashicorp/vault"


  # extraLabels:
  #   vault-active: "true"

  logLevel: "debug"

  resources:
    requests:
      memory: 5Gi
      cpu: 1
    limits:
      memory: 12Gi
      cpu: 2
  
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/issuer: letsencrypt
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    paths: 
      -  / 
    pathType: ImplementationSpecific
    hosts:
      - host: <hidden>
    tls:
      - secretName: vault-cert
        hosts:
          -  <hidden>

  auditStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/audit"
    accessMode: ReadWriteOnce

  volumes: 
    - name: tls
      secret:
        secretName: vault-internal

  volumeMounts: 
    - name: tls
      mountPath: "/vault/userconfig/vault-internal"
      readOnly: true
      
  ha:
    enabled: true 
    replicas: 3

    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        # tls_cert_file = "/vault/userconfig/vault-internal/tls.crt"
        # tls_key_file = "/vault/userconfig/vault-internal/tls.key"
        # tls_client_ca_file = "/vault/userconfig/vault-internal/ca.crt"
        # tls_min_version = "tls12"
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "dynamodb" {
        ha_enabled = "true"
        region     = "<hidden>"
        table      = "<hidden>"
        endpoint   = "<hidden>"
      }

      seal "awskms" {
      region     = "<hidden>"
      kms_key_id = "<hidden>"
      }

      telemetry {
          prometheus_retention_time = "30s"
          disable_hostname = true
        }
      
      service_registration "kubernetes" {}
      
  serviceAccount:
    create: true
    name: "vault"
    annotations: 
      eks.amazonaws.com/role-arn: <hidden>
  
  extraEnvironmentVars: 
    VAULT_ADDR: http://127.0.0.1:8200
    # VAULT_CACERT: /vault/userconfig/vault-internal/ca.crt

  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    initialDelaySeconds: 120
    timeoutSeconds: 10
    scheme: http

  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    # When a probe fails, Kubernetes will try failureThreshold times before giving up
    failureThreshold: 2
    # Number of seconds after the container has started before probe initiates
    initialDelaySeconds: 120
    # How often (in seconds) to perform the probe
    periodSeconds: 10
    # Minimum consecutive successes for the probe to be considered successful after having failed
    successThreshold: 1
    # Number of seconds after which the probe times out.
    timeoutSeconds: 10
    scheme: http

####################

injector:
  enabled: false
```
