### ISSUE TITLE
Vault fails to start with password-less postgres connection string

### ISSUE THREAD

**Issue by adamstrawson** [hashicorp/vault#19106]
**Describe the bug**

We use GCP Cloud SQL for our Postgres databases, and we tend to favour the use of IAM database authentication (alongside the GCP Cloud SQL Proxy for encryption) over traditional user/passwords.

With IAM Authentication we don't use passwords on connection strings, but it appears Vault fails to run if a password isn't defined. 

I've tried two variations of connection string:

```
connection_url: "postgresql://localhost:5432/vault?user=vault%40{gcp_project}.iam"
OR
connection_url: "postgresql://vault%40{gcp_project}.iam@localhost:5432/vault"
```

When using connection strings without a password, we get the below error:

`server error (FATAL: empty password returned by client (SQLSTATE 28P01)) `

**To Reproduce**
- Install Vault via Helm with the below values;
```
    server:
      ha:
        enabled: true
        replicas: 3
        config:
          listener:
            tcp:
              address: "[::]:8200"
              cluster_address: "[::]:8201"
              tls_disable: 1
          storage:
            postgresql:
              connection_url: "postgresql://vault-vault%40non-production-339214.iam@localhost:5432/vault-vault"
```
- Vault will fail to start with the above error. 

**Expected behavior**

Vault Postgres client should handle connection strings without a password

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12.1
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: Kubernetes & Helm 

Vault server configuration file(s):

```hcl
{
  "disable_mlock": true,
  "listener": {
    "tcp": {
      "address": "[::]:8200",
      "cluster_address": "[::]:8201",
      "tls_disable": 1
    }
  },
  "seal": {
    "gcpckms": {
      "crypto_key": "{key}",
      "key_ring": "{key_ring}",
      "project": "{gcp_vault},
      "region": "global"
    }
  },
  "storage": {
    "postgresql": {
      "connection_url": "postgresql://localhost:5432/vault?user=vault%40{gcp_project}iam"
    }
  }
}
```

**Additional context**
