### ISSUE TITLE
Login auto auth for IBM Cloud Secrets Manager to Vault agent

### ISSUE THREAD

**Issue by ailsonfds** [hashicorp/vault#19477]
**Is your feature request related to a problem? Please describe.**
I'm recently came to work with IBM Cloud Secrets Manager and came to across with its Vault API. I soon realize that Helm Vault injection was not supported by the Vault agent for this secrets manager, as using Kubernetes deployments, I'm in need for this authentication to easier manager secret injection on the applications.

**Describe the solution you'd like**
I need that the configuration auto_auth for the Vault agent have support for the IBM Cloud Secrets Manager with trusted profile authentication from the cluster to a private Secrets Manager instance.

**Describe alternatives you've considered**
External Secrets Operator is an alternative to the problem but that create Kubernetes Secret objects on the cluster and the idea is to not have those objects and secrets being managed outside from the cluster.

**Additional context**

- Example of agent configuration
```json
{
    "auto_auth": {
        "method": {
            "type": "ibmcloud",
            "mount_path": "auth/ibmcloud",
            "config": {
                "type":"trusted_profile",
                "sa_token_path": "/var/run/secrets/tokens/sa-token",
                "profile_id": "Profile-abcdef00-0000-0000-0000-000000000000"
            }
        },
        "sink": [
            {
                "type": "file",
                "config": {
                    "path": "/home/vault/.vault-token"
                }
            }
        ]
    },
    "exit_after_auth": false,
    "pid_file": "/home/vault/.pid",
    "vault": {
        "address": "https://abcdef00-0000-0000-0000-000000000000.private.us-south.secrets-manager.appdomain.cloud"
    }
}
```

- Pod spec example
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-example
spec:
  volumes:
    - name: sa-token
      projected:
        sources:
        - serviceAccountToken:
            path: sa-token
            expirationSeconds: 3600
            audience: iam
  containers:
    - name: vault-agent
      image: docker.io/hashicorp/vault:1.12.0
      command:
        - /bin/sh
        - '-ec'
      args:
        - >-
          echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault
          agent -config=/home/vault/config.json
      env:
        - name: VAULT_LOG_LEVEL
          value: info
        - name: VAULT_LOG_FORMAT
          value: standard
        - name: VAULT_CONFIG
          value: >-
            # base64 config.json
      resources: {}
      volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: sa-token
```
