### ISSUE TITLE
Vault Agent templating: use Kubernetes annotations to inject PKI cert and key into different files

### ISSUE THREAD

**Issue by nrogerarkhn** [hashicorp/vault#19787]
**Is your feature request related to a problem? Please describe.**
I need to generate certificates for my Prometheus server on a Kubernetes cluster to use mTLS. I use the agent injector with annotations to push generated certificates into my Prometheus pod.
However, Prometheus configuration needs one file for the certificate, one file for the secret, and one file for the CA.
I use the following configuration:
```yaml
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'issuer'
        vault.hashicorp.com/agent-inject-secret-certif.pem: 'pki/issue/cert' 
        vault.hashicorp.com/agent-inject-template-certif.pem: |
          {{- with pkiCert "pki/issue/cert" "common_name=test.example.com" "ttl=2h" -}}
          {{ .Key }}{{ .Cert }}{{- end }}
```
and I get one file that I must split with some barbaric sh before feeding it to Prometheus.

If I use two `agent-inject-secret` and `agent-inject-template` (one for the crt and one for the key), it generates two different certificates and pushes the key of cert A and the certificate of cert B, so I can't use it this way:
```yaml
spec:
  template:
    spec:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'issuer'
        vault.hashicorp.com/agent-inject-secret-certif.key: 'pki/issue/cert' 
        vault.hashicorp.com/agent-inject-template-certif.key: |
          {{- with pkiCert "pki/issue/cert" "common_name=test.example.com" "ttl=2h" -}}
          {{ .Key }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-certif.crt: 'pki/issue/cert' 
        vault.hashicorp.com/agent-inject-template-certif.crt: |
          {{- with pkiCert "pki/issue/cert" "common_name=test.example.com" "ttl=2h" -}}
          {{ .Cert }}
          {{- end }}
```

**Describe the solution you'd like**

I would love it if there was a way I could push the issued cert into a variable and use it in two different templates, like this:
```yaml
spec:
  template:
    spec:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'issuer'
        vault.hashicorp.com/agent-variable-secret-<name>: 'pki/issue/cert'
        vault.hashicorp.com/agent-inject-template-certif.key: |
          {{- with pkiCert "$<name>" "common_name=test.example.com" "ttl=2h" -}}
          {{ .Key }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-certif.crt: |
          {{- with pkiCert "$<name>" "common_name=test.example.com" "ttl=2h" -}}
          {{ .Cert }}
          {{- end }}
```

**Describe alternatives you've considered**
For now I use a combination of `grep`, `split` and `xargs` "manually" but it is not elegant at all.

**Additional context**
The only post I could find was [this one](https://discuss.hashicorp.com/t/pkicert-with-consul-template-and-output-to-multiple-files/45365) leading to [this issue](https://github.com/hashicorp/consul-template/issues/1597) which isn't helpful because I'm not using Consul-template but Vault Kube Annotations, so I can't use `writeToFile`.

If this is already possible and I'm doing it the wrong way, please correct me!

Thanks in advance.
