### ISSUE TITLE
Unable to copy vault.hcl configuration from host to vault docker container with docker compose

### ISSUE THREAD

**Issue by sysadmin1337** [hashicorp/vault#2053]
When starting the container with the following `docker-compose.yml` with `docker-compose up` 
```
version: '2'
services:
  vault:
    image: vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    ports:
      - "8200:8200"
    command: vault server -config=/vault/config/vault.hcl
```
I get the error:
```
Creating vault
Attaching to vault
vault    | Error loading configuration from /vault/config/vault.hcl: stat /vault/config/vault.hcl: no such file or directory
vault exited with code 1
```

The vault.hcl file is located relative to the `docker-compose.yml` at `volumes/config/vault.hcl`. Also tried absolute path, same result. The description of the vault docker image on the [hub](https://hub.docker.com/_/vault/) mentions:

> The container has a Vault configuration directory set up at /vault/config and the server will load any HCL or JSON configuration files placed here by binding a volume or by composing a new image and adding files.

Relevant portion on docker compose configuration [page](https://docs.docker.com/compose/compose-file/#/volumes-volumedriver):

```
  # Path on the host, relative to the Compose file
  - ./cache:/tmp/cache
```

How can I make this work? Maybe also improvement to include working `docker-compose.yml` on the vault description on docker hub?
