### ISSUE TITLE
failed to initialize barrier: failed to persist keyring: mkdir /vault/data/core: permission denied

### ISSUE THREAD

**Issue by Balaji-MP** [hashicorp/vault#20953]
Vault helm deployment failed in Openshift 4.12. 

Unable to perform init or unseal actions due to permission issues. 

Note: PVC has the right permissions with ReadWriteOnce and also patched an init container to grant additional privileges and still the issue persists. 

```
--> failed to initialize barrier: failed to persist keyring: mkdir /vault/data/core: permission denied
command terminated with exit code 2
```

**Comment by maxb** [comment]
Already asked at https://discuss.hashicorp.com/t/failed-to-initialize-barrier-failed-to-persist-keyring-mkdir-vault-data-core-permission-denied/54498, discussion ongoing there.

**Comment by lukmanlab** [comment]
I also got the issue when trying to use storageClass gp3. But, it can be resolved by formating the filesystem to `ext4`.

**Comment by typkrft** [comment]
If anyone stumbles across this. I ran into this issue trying to persist data via docker. The folder I was storing data in didn't have the `vault` user's UID:GID. The docker image uses 100 as the UID for the `vault` user. This user on my host system already existed as `systemd-network` and `dhcpcd` on another, which I wasn't a fan of. My solution was to create a `Dockerfile` which changed the `vault` UID and GID.

dockerfile
```dockerfile
FROM hashicorp/vault:latest
ARG UID
ARG GID
RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
RUN apk add -U shadow
RUN groupmod -g $GID vault && usermod -u $UID -g $GID vault
```

docker-compose.yml
```yaml
# Make sure GID and UID are not  in use in vault image or on the host
# sudo docker run --rm hashicorp/vault grep $GID /etc/group
# sudo docker run --rm hashicorp/vault grep $UID /etc/passwd

# To run 
# mkdir ./storage/data && sudo chown 1001:1001 ./storage/data
# sudo docker compose up -d --force-recreate --build

services:
  vault:
    container_name: vault
    build:
      context: . 
      args:
        UID: 1001
        GID: 1001
    pull_policy: always
    ports:
      - '8201:8201'
    cap_add:
      - IPC_LOCK
    command: server
    environment:
      VAULT_LOCAL_CONFIG: >
        {
          "api_addr": "...",
          "default_lease_ttl": "168h",
          "listener": {
            "tcp": {
              "address": "...",
              "tls_disable": true
            }
          },
          "max_lease_ttl": "720h",
          "storage": {"file": { "path": "/vault/data" }},
          "ui": true
        }
      TZ: US/Eastern
    volumes:
      - './storage/data:/vault/data'
    restart: unless-stopped
    healthcheck:
      retries: 5
```
