### ISSUE TITLE
Vault HA - separate Vault cluster from Consul cluster

### ISSUE THREAD

**Issue by simonkey007** [hashicorp/vault#2100]
We are interesting in setting up a Vault HA environment with Consul as a backend but separate them to two deployments. Right now with the following manifests everything works fine but additional Consul services are running on Vault instances. Is it possible to get rid of Consul services on Vault instances?

# Vault manifest
```
compilation:
  cloud_properties:
    name: random
  network: vault
  reuse_compilation_vms: true
  workers: 6
director_uuid: 28539132-6d43-4e1b-bf40-f2ce056ee9f8
jobs:
- instances: 3
  name: vault
  networks:
  - name: vault
    static_ips:
    - 10.244.8.3
    - 10.244.8.4
    - 10.244.8.5
  persistent_disk: 4096
  properties:
    consul:
      join_hosts:
      - 10.244.68.3
      - 10.244.68.4
      - 10.244.68.5
      - 10.244.68.6
      - 10.244.68.7
      - 10.244.68.8
      - 10.244.68.9
    vault:
      backend:
        use_consul: true
  resource_pool: small_z1
  templates:
  - name: consul
    release: consul
  - name: vault
    release: vault
name: vault-warden
networks:
- name: vault
  subnets:
  - gateway: 10.244.8.1
    range: 10.244.8.0/24
    static:
    - 10.244.8.2 - 10.244.8.60
  type: manual
releases:
- name: vault
  version: latest
- name: consul
  version: latest
resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: vault
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000

```
# Consul manifest

```
compilation:
  cloud_properties:
    name: random
  network: consul1
  reuse_compilation_vms: true
  workers: 6
director_uuid: 28539132-6d43-4e1b-bf40-f2ce056ee9f8
jobs:
- instances: 7
  name: consul
  networks:
  - name: consul1
    static_ips:
    - 10.244.68.3
    - 10.244.68.4
    - 10.244.68.5
    - 10.244.68.6
    - 10.244.68.7
    - 10.244.68.8
    - 10.244.68.9
  persistent_disk: 0
  properties:
    consul:
      default_recursor: null
      join_hosts:
      - 10.244.68.3
      - 10.244.68.4
      - 10.244.68.5
      - 10.244.68.6
      - 10.244.68.7
      - 10.244.68.8
      - 10.244.68.9
      services:
        example: {}
    networks:
      apps: consul1
  resource_pool: small_z1
  templates:
  - name: consul
    release: consul
  update:
    canaries: 0
    max_in_flight: 50
name: consul-warden
networks:
- name: consul1
  subnets:
  - gateway: 10.244.68.1
    name: consul1
    range: 10.244.68.0/24
    static:
    - 10.244.68.2 - 10.244.68.60
  type: manual
properties: {}
releases:
- name: consul
  version: latest
resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: consul1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 50
  serial: true
  update_watch_time: 5000-120000
```
