### ISSUE TITLE
v1.14.0 breaks AWS EKS IRSA credentials for DynamoDB backend

### ISSUE THREAD

**Issue by SeanKnight** [hashicorp/vault#21465]
**Describe the bug**

Startup logs:

```
2023-06-27T00:36:30.759Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error initializing storage of type dynamodb: NoCredentialProviders: no valid providers in chain. Deprecated.
    For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**To Reproduce**

1. Install vault on EKS cluster via helm chart (`0.23.0` or `0.25.0`) using image tag `1.14.0` 

**Expected behavior**
Vault starts up like it did on version `1.13.4`

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.14.0`
* Vault CLI Version (retrieve with `vault version`): n/a
* Server Operating System/Architecture: linux/amd64

Vault server configuration excerpt:

```hcl
storage "dynamodb" {
  ha_enabled = "true"
  region = "us-west-2"
  table = "vault"
}
```

Helm values excerpt:

```yaml
server:
  image:
    repository: "hashicorp/vault"
    tag: "1.14.0"
  serviceAccount:
    annotations:
      "eks.amazonaws.com/role-arn": MY_ROLE_ARN
```

**Additional context**
Image tag `1.13.4` works but `1.14.0` does not

Possibly related since the version of `hashicorp/go-secure-stdlib` has [changed](https://github.com/hashicorp/vault/blame/v1.14.0/go.mod#L97) in `go.mod` for vault `1.14.0`:

- https://github.com/hashicorp/go-secure-stdlib/issues/71
