### ISSUE TITLE
HA mode with consul backend, autodetect address for Cluster addres and Redirect address set invalid address

### ISSUE THREAD

**Issue by LuckySB** [hashicorp/vault#2165]
i have worked consul with 3 nodes, with address consul (10.0.0.203, .204, .205) in docker conatainer

i try 3 vault container with config

`backend "consul" {
  address = "consul:8500"
  path = "vault"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}`

after start docker logs vault show me:

`                 Backend: consul (HA available)
                     Cgo: disabled
         Cluster Address: https://10.0.0.204:8201
              Listener 1: tcp (addr: "172.19.0.9:8200", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: http://10.0.0.204:8200
                 Version: Vault v0.6.3
             Version Sha: 27aff4397f6fe6cf741fbc967adf863347c0beaf+CHANGES
`
address 10.0.0.204 - this is address of consul, not is vault docker container address!

i try set in config all address staticaly
`server.hcl
/vault/config # cat server.hcl
backend "consul" {
  address = "consul:8500"
  redirect_addr = "http://172.18.0.10:8200"
  path = "vault/"
}

listener "tcp" {
  address = "172.18.0.10:8200"
  cluster_address = "172.18.0.10:8201"
  tls_disable = 1
}
`

docker logs show good:
`==> Vault server configuration:

                 Backend: consul (HA available)
                     Cgo: disabled
         Cluster Address: https://172.18.0.10:8201
              Listener 1: tcp (addr: "172.18.0.10:8200", cluster address: "172.18.0.10:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: http://172.18.0.10:8200
                 Version: Vault v0.6.3
             Version Sha: 27aff4397f6fe6cf741fbc967adf863347c0beaf+CHANGES
`

but netstat show - vault listen only port 8200, and do not listen port 8201
why ? 

`netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 172.18.0.10:8200        0.0.0.0:*               LISTEN      6/vault
`

**Comment by jefferai** [comment]
Is that node the active node?

**Comment by jefferai** [comment]
Closed; OP posted on mailing list as well.

**Comment by danieladams456** [comment]
I'm having the same issue.  Is it possible to open the ticket again?  I'm available to help troubleshoot.

### Vault Config

```hcl
backend "consul" {
	address = "consul:8500"
	path = "vault"
}

listener "tcp" {
	address = "0.0.0.0:8200"
	cluster_address = "0.0.0.0:8201"
	tls_disable = 1
}
```

### Docker-compose logs
```
vault1_1  | 2017/02/01 20:12:05.516206 [WARN ] physical/consul: appending trailing forward slash to path
vault1_1  | ==> Vault server configuration:
vault1_1  |
vault1_1  |                  Backend: consul (HA available)
vault1_1  |                      Cgo: disabled
vault1_1  |          Cluster Address: https://172.18.0.2:8201
vault1_1  |               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")
vault1_1  |                Log Level: info
vault1_1  |                    Mlock: supported: true, enabled: true
vault1_1  |         Redirect Address: http://172.18.0.2:8200
vault1_1  |                  Version: Vault v0.6.4
vault1_1  |              Version Sha: f4adc7fa960ed8e828f94bc6785bcdbae8d1b263
vault1_1  |
vault1_1  | ==> Vault server started! Log data will stream in below:
vault1_1  |
vault2_1  | 2017/02/01 20:12:05.716475 [WARN ] physical/consul: appending trailing forward slash to path
vault2_1  | ==> Vault server configuration:
vault2_1  |
vault2_1  |                  Backend: consul (HA available)
vault2_1  |                      Cgo: disabled
vault2_1  |          Cluster Address: https://172.18.0.2:8201
vault2_1  |               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")
vault2_1  |                Log Level: info
vault2_1  |                    Mlock: supported: true, enabled: true
vault2_1  |         Redirect Address: http://172.18.0.2:8200
vault2_1  |                  Version: Vault v0.6.4
vault2_1  |              Version Sha: f4adc7fa960ed8e828f94bc6785bcdbae8d1b263
vault2_1  |
vault2_1  | ==> Vault server started! Log data will stream in below:
vault2_1  |
```

172.18.0.2 is the ip address of the consul node, not the vault node.  Note how both of them have come up with the same cluster and redirect address.

Current workaround is to force specification with the VAULT_REDIRECT_ADDR environment variable pointing to the docker dns name of the container.

```yaml
version: '2.0'

services:
  consul:
    image: consul
    command: agent -server -client 0.0.0.0 -bootstrap-expect=1 -ui
    ports:
      - 8500:8500

  vault1:
    build:
      context: .
      dockerfile: Dockerfile-vault
    command: vault server -config=/vault/config/test.hcl
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200   #for cli client to point to non https
      - VAULT_REDIRECT_ADDR=http://vault1:8200
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    ports:
      - 8200:8200

  vault2:
    build:
      context: .
      dockerfile: Dockerfile-vault
    command: vault server -config=/vault/config/test.hcl
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200   #for cli client to point to non https
      - VAULT_REDIRECT_ADDR=http://vault2:8200
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    ports:
      - 8201:8200
```
