### ISSUE TITLE
Vault as Nginx basic_auth backend

### ISSUE THREAD

**Issue by panda87** [hashicorp/vault#223]
Hi

I'm trying to understand how I can implement Vault as basic_auth backend.
So if I have some several systems on several machines I will be able to create one password for certain user, store it in Vault, and this will be accessible from the all nginx machines.

How I can call Vault from the Nginx conf file or the restricted conf file?

Thanks!

**Comment by sethvargo** [comment]
Hi @panda87 

You can use [Consul Template](https://github.com/hashicorp/consul-template) which has support for querying for secrets out of Vault.

**Comment by panda87** [comment]
Thanks for your quick answer @sethvargo 
But, I'm still trying to figure out how to insert the encrypted user:password from the .htpasswd file to the Consul and then to the Vault?

Or maybe the password won't be encrypted and then how the nginx conf file will read them? because in the auth window we pass user and password and the basic auth takes it from the .htpasswd file, now how it gonna happen?

Thanks!

**Comment by sethvargo** [comment]
Hi @panda87 

I'm not 100% sure I understand your use case, but you do not need Consul to use Consul Template. You can use the Vault component without Consul:

```
{{ with vault "secret/foo" }}
{{.Data.username}}:{{.Data.password}}
{{ end }}
```

Assume the vault key had a username and password field.

**Comment by roguh** [comment]
For anyone using `VaultSecret` in Kubernetes, I ran into this issue and used templates as recommended:

```
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: basic-auth
spec:
  path: path-to/hashed/passwords
  templates:
    auth: |-
      {%- range $k, $v := .Secrets %}
        {% $k %}:{% $v -%}
      {% end %}
  type: Opaque
```

I had to hash passwords before storing them in Vault, since the templates do not allow non-deterministic hashing functions like `bcrypt`.
