### ISSUE TITLE
Vault instance crashes when using revoked transit token instead of ending up in SEALED state.

### ISSUE THREAD

**Issue by smangels** [hashicorp/vault#23666]
**Describe the bug**
We would expect that when starting a VAULT instance (v1.15) with VAULT_TOKEN set to a revoked transit token, the instance would end up in SEALED state. Instead instance crashes and doesn't come up at all. The log indicates 403 issues returned from VAULT instance running the transit engine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run vault with valid token, check vault status => Vault is in state UNSEALED
2. Generate a new orphan token in SEED instance
3. Revoke the previously used token in SEED instance `vault token revoke <TOKEN>`
4. Inject the NEW token into Vault instance, instance crashes (Docker container)
5. Restore VAULT_TOKEN to working token - VAULT instance reaches UNSEALED state

**Expected behaviour**
A Vault instance with transit stanza that has been revoked should come up in state SEALED and not crash.

**Environment:**
* Vault Server Version 1.15
* Vault CLI Version (retrieve with `vault version`): v1.15
* Server Operating System/Architecture: MacOS Sonoma 14.0

Vault server configuration file(s):

```hcl
disable_mlock = true
ui=true

storage "file" {
  path    = "/vault/file"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = "true"
}

seal "transit" {
  address = "http://enigma-seed:8200"
  disable_renewal = "false"
  key_name = "autounseal"
  mount_path = "transit/"
  tls_skip_verify = "true"
}

api_addr = "http://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:1201"
```

**Additional context**

[errors-crash-revoked-transit-token.log](https://github.com/hashicorp/vault/files/12918285/errors-crash-revoked-transit-token.log)

**Comment by raskchanky** [comment]
@smangels When you say "crashes", do you mean the Vault instance is no longer running? Was there a panic? I see the logs you posted, which show permission denied errors. I think that's to be expected if you're using a revoked token? I don't think those errors constitute a crash though. Can you add some more details?

**Comment by smangels** [comment]
The container state in docker is Restarting, and will never be up. I've added `vault status` as health check for the container setup. Attached you will find the docker-compose file.

```yaml
version: "3.8"
services:

  enigma-seed:
    image: hashicorp/vault:1.15
    container_name: enigma-seed
    hostname: enigma-seed
    ports:
      - 8100:8200
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "token1"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_RAFT_NODE_ID: "enigma-seed-1"
      VAULT_RAFT_PATH: "/vault/file"
    healthcheck:
      retries: 2
      test: ["CMD", "/bin/vault", "status"]
      interval: 10s
      start_period: 10s
    volumes:
      - ./configs/enigma-seed/config-seed.hcl:/vault/config/config.hcl:ro
      - ./vault-data/enigma-seed:/vault/file

  enigma-master:
    image: hashicorp/vault:1.15
    container_name: enigma-master
    restart: on-failure:10
    hostname: enigma-master
    env_file:
      - ./configs/enigma-master/token.env
    depends_on:
      - enigma-seed
    command:
      - "server"
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    environment:
      # VAULT_DEV_ROOT_TOKEN_ID: "token2"
      # VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_TRANSIT_ADDR: "http://enigma-seed:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
    healthcheck:
      retries: 2
      test: ["CMD", "/bin/vault", "status"]
      interval: 10s
      start_period: 10s
    volumes: 
      - ./configs/enigma-master/config-master.hcl:/vault/config/config.hcl:ro
      - ./vault-data/enigma-master:/vault/file

volumes:
  enigma-seed:
  enigma-master:
```

![Screenshot 2023-10-17 at 08 59 03](https://github.com/hashicorp/vault/assets/4567226/a904de78-bd27-45ca-b6a5-99b456fe5a54)
