### ISSUE TITLE
API: Read AppRole secret ID returns 2xx with empty body when not found

### ISSUE THREAD

**Issue by Hansanto** [hashicorp/vault#24019]
**Describe the bug**
The endpoint [Read Secret ID](https://developer.hashicorp.com/vault/api-docs/auth/approle#read-approle-secret-id) will return an empty body with a status 2xx if the secret ID was not generated by the endpoint the [Generate Secret ID](https://developer.hashicorp.com/vault/api-docs/auth/approle#generate-new-secret-id) and therefore, not found.

However, for other endpoints (for [AppRole](https://developer.hashicorp.com/vault/api-docs/auth/approle)), when an element is not found ([Read Role](https://developer.hashicorp.com/vault/api-docs/auth/approle#read-approle), [Read Secret ID Accessor](https://developer.hashicorp.com/vault/api-docs/auth/approle#read-approle-secret-id-accessor), [List](https://developer.hashicorp.com/vault/api-docs/auth/approle#list-roles), etc.), the API will return a 4xx status code and not a 2xx with empty body.

**To Reproduce**
- [Enable approle auth method](https://developer.hashicorp.com/vault/api-docs/system/auth#enable-auth-method)
- [Create approle](https://developer.hashicorp.com/vault/api-docs/auth/approle#create-update-approle)
- [Read a secret ID](https://developer.hashicorp.com/vault/api-docs/auth/approle#read-approle-secret-id) with random value (here you will receive 2xx without body)

**Expected behavior**
The [Read secret ID](https://developer.hashicorp.com/vault/api-docs/auth/approle#read-approle-secret-id) should return 4xx if the value is not found (consistency with other endpoints)

**Environment:**
* Vault Server Version (retrieve with `vault status`):

| Key | Value |
|-----|-------|
| Seal Type | shamir |
| Initialized | true |
| Sealed | false |
| Total Shares | 1 |
| Threshold | 1 |
| Version | 1.15.1 |
| Build Date | 2023-10-20T19:16:11Z |
| Storage Type | inmem |
| Cluster Name | vault-cluster-ddafadb2 |
| Cluster ID | 2eba8a69-566e-05d8-a2f9-a3e76d591c3a |
| HA Enabled | false |

* Vault CLI Version (retrieve with `vault version`): 
Vault v1.15.1 (b94e275f25ccd9011146d14c00ea9e49fd5032dc), built 2023-10-20T19:16:11Z

* Server Operating System/Architecture: 
Docker on Windows & Linux

Vault server configuration file(s):

```yaml
# docker-compose
version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.15.1
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
```

**Additional context**
