### ISSUE TITLE
API: Endpoints change the error response format

### ISSUE THREAD

**Issue by Hansanto** [hashicorp/vault#24039]
**Describe the bug**
In almost all endpoints, when an error is  thrown by the API, the response body will be:
```json
{
  "errors": [
    "The request is invalid."
  ]
}
```
However, the endpoints:

- [Read AppRole Secret ID Accessor](https://developer.hashicorp.com/vault/api-docs/auth/approle#read-approle-secret-id-accessor)
- (Probably others)

change the response body when an error is detected. This is an example of an error with these endpoints:
```json
{
  "request_id": "66ddc2e2-cd9b-6d24-bd01-b9d56fd69021",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "error": "failed to find accessor entry for secret_id_accessor: \"test\""
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

**To Reproduce**
- [Enable approle auth method](https://developer.hashicorp.com/vault/api-docs/system/auth#enable-auth-method)
- [Read AppRole Secret ID Accessor](https://developer.hashicorp.com/vault/api-docs/auth/approle#read-approle-secret-id-accessor) with random value (check the response body)

**Expected behavior**
The error response must have the same format for the whole API;
```json
{
  "errors": [
    "The request is invalid."
  ]
}
```

**Environment:**
* Vault Server Version (retrieve with `vault status`):

| Key | Value |
|-----|-------|
| Seal Type | shamir |
| Initialized | true |
| Sealed | false |
| Total Shares | 1 |
| Threshold | 1 |
| Version | 1.15.1 |
| Build Date | 2023-10-20T19:16:11Z |
| Storage Type | inmem |
| Cluster Name | vault-cluster-ddafadb2 |
| Cluster ID | 2eba8a69-566e-05d8-a2f9-a3e76d591c3a |
| HA Enabled | false |

* Vault CLI Version (retrieve with `vault version`): 
Vault v1.15.1 (b94e275f25ccd9011146d14c00ea9e49fd5032dc), built 2023-10-20T19:16:11Z

* Server Operating System/Architecture: 
Docker on Windows & Linux

Vault server configuration file(s):

```yaml
# docker-compose
version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.15.1
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
```

**Additional context**
