### ISSUE TITLE
Error initializing listener of type tcp: error loading TLS cert: open /vault/config/cert/cert.pem: permission denied

### ISSUE THREAD

**Issue by alexdawn** [hashicorp/vault#24634]
**Describe the bug**
This probably a misconfiguration but I've not been able to solve the issue. I've disabled tls and peeked around inside the container with `docker-compose exec kms sh`, the *.pem files are there and the container is running as root. Everything is working fine without tls.

**To Reproduce**
Steps to reproduce the behaviour:
1. run `docker-compose up --build kms`
2. see `encryption_demo_vault | Error initializing listener of type tcp: error loading TLS cert: open /vault/config/cert/cert.pem: permission denied`

**Expected behaviour**
I'm expecting the container to to be brought up and run the entrypoint `command: server`

**Actions**

I've tried changing the owner of the pem files, I've tried changing their permissions to 400 encase vault was unhappy at the files being too accessible. If I disable tls with the vault config then everything works the container is running and I can visit the vault ui or connect with the vault cli tool.

**Environment:**
* docker image `vault:1.13.3`
* docker `Docker version 24.0.7, build afdd53b`
* docker-compose `docker-compose version 1.29.2, build unknown`

Vault server configuration file(s):

```json
{
    "storage": {
        "file": {
            "path": "/vault/file"
        }
    },
    "listener": [
        {
            "tcp": {
                "_comment": "don't use localhost or only the container can get to the ui",
                "address": "0.0.0.0:8200",
                "tls_disable": false,
                "tls_cert_file": "/vault/config/cert/cert.pem",
                "tls_key_file": "/vault/config/cert/key.pem"
            }
        }
    ],
    "api_addr": "https://127.0.0.1:8200",
    "cluster_addr": "https://127.0.0.1:8201",
    "default_lease_ttl": "168h",
    "max_lease_ttl": "720h",
    "ui": true,
    "log_file": "/vault/logs/log",
    "log_rotate_duration": "24h",
    "log_rotate_max_files": 30
}
```

docker compose file (other containers have been removed from snippet):
```
# ./docker-compose.yml

version: '3'

services:
  kms:
    image: vault:1.13.3
    container_name: encryption_demo_vault
    environment:
      VAULT_ADDR: https://127.0.0.1:8200
      VAULT_CLIENT_CERT: "/vault/config/cert/cert.pem"
      VAULT_CLIENT_KEY: "/vault/config/cert/key.pem"
    volumes:
      - "./vault/logs:/vault/logs"
      - "./vault/file:/vault/file"
      - "./vault/config:/vault/config"
    ports:
      - "8200:8200"
      - "8201:8201"
    cap_add:
      - IPC_LOCK
    command: server
    # it finds the config by default setting the flag is bugged --config=/vault/config/config.json

```

**context**

I've got a prototype project and have moved from vault in dev mode to trying to run vault in prod mode to get an idea of what deployment hurdles there will be.
