### ISSUE TITLE
vault_core_unsealed metric disappears after prometheus_retention_time elapses

### ISSUE THREAD

**Issue by cascadia-sati** [hashicorp/vault#24741]
**Describe the bug**
I'm using the Vault Helm chart to deploy Vault to our K8s cluster using a three-replica HA setup. While working on monitoring for the seal status, I noticed that the `vault_core_unsealed` metric mysteriously disappears after some time. [This discussion](https://discuss.hashicorp.com/t/monitoring-vault-seal-status/46413/6) hinted that it may be due to the `prometheus_retention_time` config field. That does indeed seem to be the case.

Increasing it does make the metric stick around longer, but only until the retention time elapses. When the seal status does change, the metric comes back, and alerting can kick in, but in the meantime our dashboards and alerts show "no data", which is not ideal.

**To Reproduce**
Simply install Vault and watch the `vault_core_unsealed` metric disappear after `prometheus_retention_time` amount of time.

**Expected behavior**
The `vault_core_unsealed` metric should persist, even if it doesn't change. I'm assuming Vault needs to be modified to publish the metric periodically instead of only when it's changed.

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.14.0
* Vault CLI Version (retrieve with `vault version`): v1.14.0
* Server Operating System/Architecture: Vault running on Kubernetes EKS installed via v0.25.0 of the Vault Helm chart

Vault server configuration file(s):
(My Helm values file with the Vault config embedded)
```yaml
global:
  serverTelemetry:
    prometheusOperator: true
injector:
  enabled: false
server:
  ha:
    enabled: true
    replicas: 3
    # Enable HA for integrated storage
    raft:
      enabled: true
      setNodeId: true
      config: |
        # Setting the cluster name here avoids duplicate metrics:
        # https://github.com/hashicorp/vault/issues/11988
        cluster_name = "pace-vault"

        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"

          # Enable unauthenticated metrics access for Prometheus Operator
          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }

        telemetry {
          prometheus_retention_time = "30m"
          disable_hostname = true
        }

        storage "raft" {
          path = "/vault/data"
        }

        # For integrated raft storage and security
        # https://developer.hashicorp.com/vault/docs/configuration#disable_mlock
        disable_mlock = true

        service_registration "kubernetes" {}
  serverTelemetry:
    serviceMonitor:
      enabled: true
  dataStorage:
    enabled: true
    size: 5Gi
    storageClass: ebs-gp3
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: server
          topologyKey: topology.kubernetes.io/zone

```

**Additional context**
