### ISSUE TITLE
Failed Raft initialization only in Docker Swarm

### ISSUE THREAD

**Issue by GiamBoscaro** [hashicorp/vault#24837]
**Describe the bug**
I am deploying a Vault service with Docker Swarm. When the containers launch, I get the error:

`Error initializing storage of type raft: failed to create fsm: failed to open bolt file: open /opt/vault/data/raft/vault.db: permission denied`

**To Reproduce**

```yaml
version: '3.8'

networks:
  vault-network:
    name: vault-network
    driver: overlay
  traefik_public:
    external: true

volumes:
  vault-data:
    name: vault-data
    driver: local

services:

  vc-vault:
    image: hashicorp/vault:1.15.2
    hostname: "{{.Node.ID}}-{{.Service.Name}}"
    volumes:
      - vault-data:/opt/vault/data/raft
      - /home/root/vault/vault.json:/vault/config/vault.json:ro
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    networks: 
      - vault-network
      - traefik_public
    ports:
      - 8200:8200
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "--tries=1", "http://127.0.0.1:8200/v1/sys/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    cap_add:
      - IPC_LOCK
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
```

**Expected behavior**
Raft storage should be initialized normally

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.2
* Server Operating System/Architecture: Ubuntu 18.04

Vault server configuration file(s):

```json
{
  "storage": {
    "raft": {
      "path": "/opt/vault/data/raft",
      "node_id": "vault_node_1"
    }
  },
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "tls_disable": true
    }
  },
  "cluster_name": "vc",
  "api_addr": "http://10.20.111.50:8200", // temporary, for test purpose
  "cluster_addr": "http://10.20.111.50:8200",
  "ui": true,
  "disable_mlock": true,
  "log_level": "debug",
  "log_format": "json",
  "default_lease_ttl": "168h",
  "max_lease_ttl": "0h"
}
```

**Additional context**
I have tested the deployment without Docker Swarm, using a normal docker compose. I have deployed Vault in the same server, using the same name for the Volume (that I then deleted) and it is working normally! It is just with Docker Swarm that I have this problem.

```yaml
version: '3.8'
services:
  vault:
    extends:
      service: vault
      file: docker-compose.yml
    build:
      target: stage
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - vault-data:/vault/data
    cap_add:
      - IPC_LOCK
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
  vc-network-stage:
    external: true

volumes:
  vault-data:
    name: "vault-data"
```

```docker
hashicorp/vault:1.15.2 AS builder

ARG DEFAULT_PORT=8200

ENV PORT $DEFAULT_PORT

WORKDIR /vault

FROM builder AS dev

# Copy config
COPY config/vault.dev.json /vault/config/vault.json

# Run server
EXPOSE $PORT
ENTRYPOINT [ "vault", "server", "-config=/vault/config/vault.json" ]

FROM builder AS stage

# Copy config
COPY config/vault.stage.json /vault/config/vault.json

# Run server
EXPOSE $PORT
ENTRYPOINT [ "vault", "server", "-config=/vault/config/vault.json" ]

FROM builder AS prod

# Copy config
COPY config/vault.json /vault/config/vault.json

# Run server
EXPOSE $PORT
ENTRYPOINT [ "vault", "server", "-config=/vault/config/vault.json" ]
```
