### ISSUE TITLE
Vault raft join error "Preventing server addition that would require removal of too many servers and cause cluster instability"

### ISSUE THREAD

**Issue by alexdawn** [hashicorp/vault#24877]
**Describe the bug**
Trying to copy the tutorial given in <https://developer.hashicorp.com/vault/tutorials/raft/raft-storage> I am trying to bring up my own cluster using docker-compose. At the step of `vault operator raft join` I'm getting the following error. I am able to run the tutorial repo just fine when the vault servers are all on my physical host.

```
URL: POST http://vault3:8200/v1/sys/storage/raft/join
Code: 500. Errors:

* failed to join raft cluster: failed to send answer to raft leader node: Error making API request.

URL: PUT http://vault2:8200/v1/sys/storage/raft/bootstrap/answer
Code: 500. Errors:

* Preventing server addition that would require removal of too many servers and cause cluster instability
```
as far as I can tell the leader node is up correctly and the auto-unseal is working. However neither vault3 nor vault4 is able to join the cluster. A google search and a search of the vault repo has no hits for the 500 error messages.

I don't understand I'm asking to add a node not remove anything? I've tried various flag options for the raft join command with no success. I'm getting similar errors with the auto_join configuration as well. I've tried joining with both a initialized and uninitialized, sealed and unsealed vault (instructions differ for `storage` and `ha_storage`), I believe I am following the right instructions for `storage` mode?

**To Reproduce**
1. Run `docker-compose up`
2. Run `docker-compose exec vault3 /bin/sh`
3. try and join vault3 to vault2 by running `vault operator raft join http://vault2:8200`

**Expected behavior**
Same behaviour as in the tutorial <https://developer.hashicorp.com/vault/tutorials/raft/raft-storage> expect a success response to the raft join and expect `raft list-peers` to show the new follower node.

**Environment:** all containers the same:
* Vault Server Version (retrieve with `vault status`): `Version                  1.14.8`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.14.8 (446f213c47cabf47d52d065647ef666ce4bf8692), built 2023-12-04T17:45:23Z`
* Server Operating System/Architecture: Ubuntu 22.04.3 LTS running official docker file image: `hashicorp/vault:1.14`

Vault server configuration file(s):

**docker-compose**
```yaml
# ./docker-compose.yml

version: '3'

services:
  vault_init: # uses the vault client to configure vaults
    container_name: encryption_demo_vault_init
    build:
      context: ./vault_raft_setup
      args:
        UID: ${CRYPT_DEMO_UID:-1000}
        GID: ${CRYPT_DEMO_GID:-1000}
        UNAME: ${CRYPT_DEMO_USERNAME:-alex}
    volumes:
      - ./tokens:/vault/tokens
    command: [
      "/vault/tokens/setup-restore.sh > /vault/tokens/setup.log 2>&1"
    ]
    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/tokens/unseal-token.txt"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      vault1:
        condition: service_started
  vault1: # for the autounseal
    image: hashicorp/vault:1.14
    container_name: encryption_demo_vault1
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      # VAULT_CLIENT_CERT: "/vault/config/cert/cert.pem"
      # VAULT_CLIENT_KEY: "/vault/config/cert/key.pem"
      VAULT_RAFT_NODE_ID: node1
    volumes:
      - "./vault1/logs:/vault/logs"
      - "./vault1/file:/vault/file"
      - "./vault1/config:/vault/config"
      - ./tokens:/vault/tokens
    ports:
      - "8200:8200"
      - "8201:8201"
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "-c"]
    command: [
      "vault server -log-level=trace -config \"/vault/config/config.json\" > \"/vault/logs/out.log\" 2>&1"
    ]
    healthcheck:
      test: ["CMD-SHELL", "VAULT_ADDR=http://localhost:8200 vault status"] # sealed vault status is non-zero
      interval: 10s
      timeout: 5s
      retries: 5
  vault2: # initial leader node
    image: hashicorp/vault:1.14
    container_name: encryption_demo_vault2
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      # VAULT_CLIENT_CERT: "/vault/config/cert/cert.pem"
      # VAULT_CLIENT_KEY: "/vault/config/cert/key.pem"
      VAULT_RAFT_NODE_ID: node2
    volumes:
      - "./vault2/logs:/vault/logs"
      - "./vault2/file:/vault/file"
      - "./vault2/config:/vault/config"
      - ./tokens:/vault/tokens
    ports:
      - "8210:8200"
      - "8211:8201"
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "-c"]
    command: [
      "export VAULT_TOKEN=$$(cat ./vault/tokens/unseal-token.txt) && vault server -log-level=trace -config \"/vault/config/config.json\" > \"/vault/logs/out.log\" 2>&1"
    ]
    healthcheck:
      test: ["CMD-SHELL", "VAULT_ADDR=http://localhost:8200 vault status"] # sealed vault status is non-zero
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      vault_init:
        condition: service_healthy
  vault3: # initial follower node
    image: hashicorp/vault:1.14
    container_name: encryption_demo_vault3
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      # VAULT_CLIENT_CERT: "/vault/config/cert/cert.pem"
      # VAULT_CLIENT_KEY: "/vault/config/cert/key.pem"
      VAULT_RAFT_NODE_ID: node3
    volumes:
      - "./vault3/logs:/vault/logs"
      - "./vault3/file:/vault/file"
      - "./vault3/config:/vault/config"
      - ./tokens:/vault/tokens
    ports:
      - "8220:8200"
      - "8221:8201"
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "-c"]
    command: [
      "export VAULT_TOKEN=$$(cat ./vault/tokens/unseal-token.txt) && vault server -log-level=trace -config \"/vault/config/config.json\" > \"/vault/logs/out.log\" 2>&1"
    ]
    healthcheck:
      test: ["CMD-SHELL", "VAULT_ADDR=http://localhost:8200 vault status"] # sealed vault status is non-zero
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      vault_init:
        condition: service_healthy
      vault2:
        condition: service_healthy
  vault4: # initial follower node
    image: hashicorp/vault:1.14
    container_name: encryption_demo_vault4
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      # VAULT_CLIENT_CERT: "/vault/config/cert/cert.pem"
      # VAULT_CLIENT_KEY: "/vault/config/cert/key.pem"
      VAULT_RAFT_NODE_ID: node4
    volumes:
      - "./vault4/logs:/vault/logs"
      - "./vault4/file:/vault/file"
      - "./vault4/config:/vault/config"
      - ./tokens:/vault/tokens
    ports:
      - "8230:8200"
      - "8231:8201"
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "-c"]
    command: [
      "export VAULT_TOKEN=$$(cat ./vault/tokens/unseal-token.txt) && vault server -log-level=trace -config \"/vault/config/config.json\" > \"/vault/logs/out.log\" 2>&1"
    ]
    healthcheck:
      test: ["CMD-SHELL", "VAULT_ADDR=http://localhost:8200 vault status"] # sealed vault status is non-zero
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      vault_init:
        condition: service_healthy
      vault2:
        condition: service_healthy
```
*./vault_raft_setup/dockerfile*

an ubuntu environment with vault. The setup bash script to configure the vault1-4 nodes is run from here

```yaml
# the vault image is pretty minimal (e.g. no bash) this a a full feature container
# with the vault client used to setup the raft cluster
FROM ubuntu:latest

RUN apt-get update && apt-get install -yq jq

# get vault
RUN  apt-get update && apt-get install -yq gpg wget
RUN  wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN  gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
RUN  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main" > /etc/apt/sources.list.d/hashicorp.list
RUN  apt-get update && apt-get install -yq vault

# mirror host user
ARG UID
ARG GID
ARG UNAME

RUN groupadd --gid "${GID}" "${UNAME}"
RUN useradd --create-home --uid "${UID}" --gid "${GID}" --shell /bin/bash "${UNAME}"

USER $UNAME

ENTRYPOINT [ "/bin/bash", "-c" ]
CMD [ "vault status" ]
```

*vault1.config*
```json
{
    "storage": {
        "inmem": {}
    },
    "listener": [
        {
            "tcp": {
                "_comment": "don't use localhost or only the container can get to the ui",
                "address": "0.0.0.0:8200",
                "cluster_address": "0.0.0.0:8201",
                "tls_disable": true,
                "tls_cert_file": "/vault/config/cert/cert.pem",
                "tls_key_file": "/vault/config/cert/key.pem"
            }
        }
    ],
    "api_addr": "http://127.0.0.1:8200",
    "cluster_addr": "http://127.0.0.1:8201",
    "default_lease_ttl": "168h",
    "max_lease_ttl": "720h",
    "ui": true,
    "log_file": "/vault/logs/log",
    "log_rotate_duration": "24h",
    "log_rotate_max_files": 30
}
```

*vault2.config*
```json
{
    "storage": {
        "raft": {
            "path": "/vault/file",
            "node_id": "vault2"
        }
    },
    "listener": [
        {
            "tcp": {
                "_comment": "don't use localhost or only the container can get to the ui",
                "address": "0.0.0.0:8200",
                "cluster_address": "0.0.0.0:8201",
                "tls_disable": true,
                "tls_cert_file": "/vault/config/cert/cert.pem",
                "tls_key_file": "/vault/config/cert/key.pem"
            }
        }
    ],
    "seal": {
        "transit": {
            "address": "http://vault1:8200",
            "disable_renewal": false,
            "key_name": "autounseal",
            "mount_path": "transit/",
            "tls_skip_verify": true
        }
    },
    "api_addr": "http://127.0.0.1:8200",
    "cluster_addr": "http://127.0.0.1:8201",
    "default_lease_ttl": "168h",
    "max_lease_ttl": "720h",
    "ui": true,
    "log_file": "/vault/logs/log",
    "log_rotate_duration": "24h",
    "log_rotate_max_files": 30
}
```

*vault3.config*
```json
{
    "storage": {
        "raft": {
            "path": "/vault/file",
            "node_id": "vault3"
        }
    },
    "listener": [
        {
            "tcp": {
                "_comment": "don't use localhost or only the container can get to the ui",
                "address": "0.0.0.0:8200",
                "cluster_address": "0.0.0.0:8201",
                "tls_disable": true,
                "tls_cert_file": "/vault/config/cert/cert.pem",
                "tls_key_file": "/vault/config/cert/key.pem"
            }
        }
    ],
    "seal": {
        "transit": {
            "address": "http://vault1:8200",
            "disable_renewal": false,
            "key_name": "autounseal",
            "mount_path": "transit/",
            "tls_skip_verify": true
        }
    },
    "api_addr": "http://127.0.0.1:8200",
    "cluster_addr": "http://127.0.0.1:8201",
    "default_lease_ttl": "168h",
    "max_lease_ttl": "720h",
    "ui": true,
    "log_file": "/vault/logs/log",
    "log_rotate_duration": "24h",
    "log_rotate_max_files": 30
}
```

*vault4.config*
```json
{
    "storage": {
        "raft": {
            "path": "/vault/file",
            "node_id": "vaul4"
        }
    },
    "listener": [
        {
            "tcp": {
                "_comment": "don't use localhost or only the container can get to the ui",
                "address": "0.0.0.0:8200",
                "cluster_address": "0.0.0.0:8201",
                "tls_disable": true,
                "tls_cert_file": "/vault/config/cert/cert.pem",
                "tls_key_file": "/vault/config/cert/key.pem"
            }
        }
    ],
    "seal": {
        "transit": {
            "address": "http://vault1:8200",
            "disable_renewal": false,
            "key_name": "autounseal",
            "mount_path": "transit/",
            "tls_skip_verify": true
        }
    },
    "api_addr": "http://127.0.0.1:8200",
    "cluster_addr": "http://127.0.0.1:8201",
    "default_lease_ttl": "168h",
    "max_lease_ttl": "720h",
    "ui": true,
    "log_file": "/vault/logs/log",
    "log_rotate_duration": "24h",
    "log_rotate_max_files": 30
}
```

*setup-restore.sh*
```bash
#!/bin/bash

set -euo pipefail

export VAULT1_UNSEAL_FILE="/vault/tokens/vault1-unseal.json"
export VAULT2_UNSEAL_FILE="/vault/tokens/vault2-unseal.json"
export VAULT_ADDR="http://vault1:8200"

sleep 1
if vault status ; then
    echo "vault cluster already configured"
    echo "unsealing vault1"
    sealKey=$(cat $VAULT1_UNSEAL_FILE | jq --raw-output .unseal_keys_b64[0])
    vault operator unseal $sealKey
    echo "unsealing vault2"
    export VAULT_ADDR="http://vault2:8210"
    vault operator unseal $sealKey

else
    echo "new container detected"
    ## vault 1
    vault operator init --format=json --key-shares=1 --key-threshold=1 > $VAULT1_UNSEAL_FILE
    sealKey=$(cat $VAULT1_UNSEAL_FILE | jq --raw-output .unseal_keys_b64[0])
    token=$(cat $VAULT1_UNSEAL_FILE | jq --raw-output .root_token)
    vault operator unseal $sealKey
    vault login $token
    # first time need to enable configure a lot of parts
    vault audit enable file file_path=/vault/logs/audit.log
    vault secrets enable transit
    # vault auth enable approle
    vault write -f transit/keys/autounseal
    # vault write -f transit/keys/crypt
    # vault write -f transit/keys/auth
    # vault write -f transit/keys/index
    vault policy write autounseal -<<EOF
        path "transit/encrypt/autounseal" {
            capabilities = [ "update" ]
        }

        path "transit/decrypt/autounseal" {
            capabilities = [ "update" ]
        }
EOF
    vault token create --orphan --policy="autounseal" \
        --wrap-ttl=120 --period=24h \
        --field=wrapping_token > /vault/tokens/wrapping-token.txt
    export VAULT_TOKEN=$(vault unwrap --field=token $(cat /vault/tokens/wrapping-token.txt))
    echo $VAULT_TOKEN > /vault/tokens/unseal-token.txt

    ## vault 2
    export VAULT_ADDR="http://vault2:8200"
    while [[ "$(vault status --format=json | jq -r .initialized)" != "true" ]] ; do
        echo "attempt init"
        INIT_RESPONSE2=$(vault operator init -format=json -recovery-shares 1 -recovery-threshold 1) || echo "retry"
        sleep 5 # give a moment for vault2 to come up
    done
    echo $INIT_RESPONSE2 > /vault/tokens/vault2-unseal.json
    RECOVERY_KEY2=$(echo "$INIT_RESPONSE2" | jq -r .recovery_keys_b64[0])
    VAULT_TOKEN2=$(echo "$INIT_RESPONSE2" | jq -r .root_token)
    sleep 5 # wait for initial setup
    # vault login "$VAULT_TOKEN2" no need to login after init
    VAULT_TOKEN=$VAULT_TOKEN2 vault secrets enable -path=kv kv-v2
    VAULT_TOKEN=$VAULT_TOKEN2 vault kv put kv/apikey webapp=ABB39KKPTWOR832JGNLS02
    VAULT_TOKEN=$VAULT_TOKEN2 vault kv get kv/apikey

    ## vault 3
    export VAULT_ADDR="http://vault3:8200"
    while [[ "$(vault status --format=json | jq -r .initialized)" != "true" ]] ; do
        echo "attempt join vault 3"
        vault operator raft join http://vault2:8200 || echo "retry" # never gets past here due to the 500 error
        sleep 5 # give a moment for vault2 to come up
    done

    ## vault 4
    export VAULT_ADDR="http://vault2:8200"
    while [[ "$(vault status --format=json | jq -r .initialized)" != "true" ]] ; do
        echo "attempt join vault 4"
        vault operator raft join http://vault2:8200 || echo "retry"
        sleep 5 # give a moment for vault2 to come up
    done
fi
```
