### ISSUE TITLE
Allow helm deployment to run in dev mode with tls enabled

### ISSUE THREAD

**Issue by Ruddickmg** [hashicorp/vault#28462]
Is your feature request related to a problem? Please describe.
I am testing a helm chart that I am deploying that has vault as a dependency, I would like to use tls while running the chart tests to ensure tls communication is working properly and covered in my integration tests. Currently with vault's helm values.yaml file, I am unable to configure vault to be both in dev mode and use tls. 

Describe the solution you'd like
I would like to be able to configure vault to use tls while in dev mode via helm values.yaml.

Describe alternatives you've considered
Setting vault up in production mode might work, but would dramatically increase the complexity and set up of tests

Note:
This has been [addressed here](https://github.com/hashicorp/vault/issues/13467), but it does not seem like the same functionality has been made available in the helm deployment configuration (values.yaml)

**Comment by sylvain-blot-sp** [comment]
Here is a little "hack" to get around this:

```
global:
  name: ""
  tlsDisable: true
ui:
  service:
    enabled: true
    type: 'ClusterIP'
server:
  extraArgs: >-
    -log-level=debug
    -config=/home/vault/config.hcl

  dev:
    enabled: true

  volumes:
    - name: vault-tls
      secret:
        secretName: "vault-certs"
        items:
          - key: "tls.crt"
            path: "tls.crt"
          - key: "tls.key"
            path: "tls.key"
  volumeMounts:
    - mountPath: /vault/tls
      name: vault-tls
      readOnly: true

  extraInitContainers:
    - name: vault-generate-tls-config
      image: hashicorp/vault:1.20.1
      command: [sh, -c]
      args:
        - echo 'listener "tcp" {' > /home/vault/config.hcl
          && echo 'address = "0.0.0.0:8400"' >> /home/vault/config.hcl
          && echo 'tls_cert_file = "/vault/tls/tls.crt"' >> /home/vault/config.hcl
          && echo 'tls_key_file  = "/vault/tls/tls.key"' >> /home/vault/config.hcl
          && echo '}' >> /home/vault/config.hcl
          && cat /home/vault/config.hcl
      volumeMounts:
        - name: home
          mountPath: /home/vault

  service:
    enabled: true
    port: 8400
    targetPort: 8400
```
