### ISSUE TITLE
Vault UI cant be accssed on /vault path via Ingress Resource

### ISSUE THREAD

**Issue by Phanindra-Sangers** [hashicorp/vault#29443]
Problem statement:

I Deployed Banks Vault in my on_prem servers and i want to access vault UI on " /vault" path for my nginx ingress controller via path based routing.

How ever , i am unable to access the vault UI on " /vault " path but the UI is accessible on root path " / "

here is my ingress file for reference :

```
`  ingress:

    annotations: {}
          nginx.ingress.kubernetes.io/rewrite-target: /$1
          ingress.kubernetes.io/protocol: https
          ingress.kubernetes.io/secure-backends: "true"
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS

    spec: {}
         ingressClassName: nginx
         rules:
         -  http: 
                 paths:
                 -    backend:
                            service:
                                 name: vault
                                  port: 8200
                      path:  /vault ## not working
                      pathTye: ImplementationSpecific `
```
