### ISSUE TITLE
GCP auto unseal doesn't work with GOOGLE_CREDENTIALS

### ISSUE THREAD

**Issue by vkanproton** [hashicorp/vault#30387]
**Describe the bug**
Vault cluster deployed on kubernetes using helm can't auto unseal its nodes when GOOGLE_CREDENTIALS is used for authentication against GCP KMS.

Passing GOOGLE_APPLICATION_CREDENTIALS works as expected.

My goal is to avoid having a file with GCP credentials.

**To Reproduce**
Environment variables snippet:
```
extraSecretEnvironmentVars:
    - envName: GOOGLE_CREDENTIALS
      secretName: vault-gcp
      secretKey: vault-gcp-unseal-service-account-json
```

Seal snippet
```
seal "gcpckms" {
project     = "_project_"
    region      = "global"
    key_ring    = "_keyring_" 
    crypto_key  = "_key_"
}
```

The same k8s secret with the same seal config works when passing GOOGLE_APPLICATION_CREDENTIALS
```
volumes:
        - name: userconfig-gcp
          secret:
            defaultMode: 420
            secretName: vault-gcp

volumeMounts:
        - mountPath: /vault/userconfig/userconfig_gcp
          name: userconfig-gcp
          readOnly: true

extraEnvironmentVars:
        GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/userconfig_gcp/vault-gcp-unseal-service-account-json
```

**Expected behavior**
I expect PODs to auto unseal the same way with `GOOGLE_CREDENTIALS` as with `GOOGLE_APPLICATION_CREDENTIALS`.

**Environment:**
Vault v1.19.1
Server Version: v1.29
