### ISSUE TITLE
Allow Vault to directly integrate with kubeconfig / kubectl for dynamic token generation

### ISSUE THREAD

**Issue by timmjd** [hashicorp/vault#30973]
**Is your feature request related to a problem? Please describe.**
I'd like to use Vault to generate Kubernetes tokens in a dynamic and fully integrated way, the same way [AWS describes](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html) it.

**Describe the solution you'd like**
The AWS mechanism internally uses the AWS CLI to dynamically generate a kubernetes token (see [update-kubeconfig](https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html)). To achieve this, the `kubeconfig` will contain an `exec` definition inside the `user` section where the `aws-cli` gets called.

**Describe alternatives you've considered**
This can be solved in different ways:
* The Vault CLI could provide a mode, where it will return a `ExecCredentials`, so it could be called be directly like the `aws` example.
* The token returned from Vault must be converted into the expected `ExecCredentials` format by an external script.

**Additional context**
If you have the AWS account credentials exposed via the defined mechanisms like environment variables (`AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KE`), and provide a `kubeconfig` file like the following, the token generation is done as a encapsulated from within the `kubectl` context. Therefore such mechanism is quiet user friendly.

```yaml
---
apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    certificate-authority-data: ***
    server: https://***.eks.amazonaws.com
  name: cluster
contexts:
- context:
    cluster: cluster
    user: user
  name: context
current-context: context
users:
- name: user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - --region
      - < AWS_REGION >
      - eks
      - get-token
      - --cluster-name
      - < my_cluster >
      - --output
      - json
```

Internally the mechanism used here is based on the `exec` or [ExecConfig](https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#ExecConfig) where the AWS-CLI returns the data as an [ExecCredentials](https://kubernetes.io/docs/reference/config-api/client-authentication.v1beta1/) format, including either a `token` or `certificate`.

```json
{
  "apiVersion": "client.authentication.k8s.io/v1beta1",
  "status": {
    "token": "***"
  }
}
```
