### ISSUE TITLE
S3 backend should not be AWS-specfic

### ISSUE THREAD

**Issue by jpds** [hashicorp/vault#3728]
**Feature Request:**

The S3 storage backend in Vault should not be specifically tied to AWS itself. There are other technologies out there which provide S3 compatible services (Ceph RADOS GW, Minio) which interface with standard commands such as `s3cmd`.

**Comment by jpds** [comment]
Related: #2274.

**Comment by jpds** [comment]
The documentation here is also really confusing: https://www.vaultproject.io/docs/configuration/storage/s3.html

```
endpoint (string: "") – Specifies an alternative, AWS compatible, S3 endpoint. This can also be provided via the environment variable AWS_S3_ENDPOINT.

region (string "us-east-1") – Specifies the AWS region. This can also be provided via the environment variable AWS_REGION or AWS_DEFAULT_REGION, in that order of preference.
```

Endpoint suggests that it is possible to choose an alternative, however, I configure Vault with:

```
 storage:
      s3:
        endpoint: "http://url/"
        access_key: "..."
        secret_key: "..."
        bucket: "vault-test"
        region: ""
```

And then Vault starts up with:

```
Error initializing storage of type s3: unable to access bucket 'vault-test' in region us-east-1: RequestError: send request failed
caused by: Get http://vault-test.url/: dial tcp: lookup vault-production.url on dns:53: no such host
```
