### ISSUE TITLE
HCL Function to extract environment variables from config files

### ISSUE THREAD

**Issue by bobbytables** [hashicorp/vault#3757]
**Feature Request:**

Hi, I'm setting up vault and I'd like to use an environment variable that gets interpolated into the HCL config file. This would be a `DATABASE_URL` that I can use in the `storage` portion of config. As an example of what I'd like to do:

```hcl
storage "postgresql" {
  connection_url = "${env(DATABASE_URL)}"
}
```

I can't see anything in the docs about this and looking through the command parser of Vault I don't see it in there either.

The reason this would help is because we're deploying Vault to a kubernetes cluster. We're storing the config file as a `ConfigMap` and then mounting that config data inside of the vault pod. Inside of the vault pod we're exporting a `DATABASE_URL` env var from a `Secret` stored in the K8s cluster.

**Comment by jefferai** [comment]
Take a look at https://github.com/hashicorp/consul-template or https://github.com/hashicorp/envconsul for this, that's what they're designed for!

**Comment by m1pl** [comment]
@jefferai Is this answer still up to date, is there still no possibility to use env vars directly in hcl files?

**Comment by jefferai** [comment]
There isn't currently, although Boundary has made some improvements here that could be pulled into Vault as well.

**Comment by m1pl** [comment]
Please do, would be nice. We want to set up Vault to manage our secrets. We don't want to set up Consul just to manage the DB credentials for Vault ^^

**Comment by gresco** [comment]
@m1pl I am not sure what your desired setup looks like, but we ran into this same bind at my job while setting up Vault in kubernetes (EKS) via helm (image we are using is `hashicorp/vault:1.9.3`). 

After a lot of digging and failed attempts, we came up echo'ing-to-file the storage config from a string of JSON added via an ENV variable in values.yaml. Then we used `sed` to swap out the placeholder password for the real MySQL password referenced as another ENV variable through `extraSecretEnvironmentVars` (from a previously added sealed secret). Afterwhich this updated JSON config file is ref'ed in the `extraArgs` section of the values.yaml file.

I did find it necessary to also add an extra volume to drop the config file into, per the `/vault/config` dir was frustratingly throwing permission denied.

Here is the pertinent blocks of YAML code from our values.yaml file, with some scrubbing for sensitive values:

```
  # Used to define commands to run after the pod is ready.
  # This can be used to automate processes such as initialization
  # or boostrapping auth methods.
  postStart:
   - /bin/sh
   - -c
   - echo $VAULT_JSON_CONFIG > /usr/local/vault/storage_config.json && sed -i -e "s/MYSQL_PASSWORD_PLACEHOLDER/$MYSQL_PWD/g" /usr/local/vault/storage_config.json

  # extraEnvironmentVars is a list of extra environment variables to set with the stateful set. These could be
  # used to include variables required for auto-unseal.
  extraEnvironmentVars: {
    AWS_REGION: "ca-central-1",    
    VAULT_JSON_CONFIG: "{ \"storage\": {\"mysql\": { \"username\": \"vault\", \"password\": \"MYSQL_PASSWORD_PLACEHOLDER\", \"database\": \"vault\", \"address\": \"ca-central-1-vault.address.ca-central-1.rds.amazonaws.com:3306\", \"ha_enabled\": \"true\" } } }"
  }
  
  # extraSecretEnvironmentVars is a list of extra environment variables to set with the stateful set.
  # These variables take value from existing Secret objects.
  extraSecretEnvironmentVars:
    - envName: MYSQL_PWD
      secretName: mysql-pwd
      secretKey: MYSQL_PWD

  # volumes is a list of volumes made available to all containers. These are rendered
  # via toYaml rather than pre-processed like the extraVolumes value.
  # The purpose is to make it easy to share volumes between containers.
  volumes:
    - name: extraconfig
      emptyDir: {}

  # volumeMounts is a list of volumeMounts for the main server container. These are rendered
  # via toYaml rather than pre-processed like the extraVolumes value.
  # The purpose is to make it easy to share volumes between containers.
  volumeMounts:
     - mountPath: /usr/local/vault
       name: extraconfig
       readOnly: false

  # extraArgs is a string containing additional Vault server arguments.
  extraArgs: "-config=/usr/local/vault/storage_config.json"
```

This is definitely more complex than I would have hoped for, but I can confirm on my end it does work.

There are other [suggestions](https://serverfault.com/questions/1090820/vault-configuration-supports-environment-variables) out [there](https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations) for which I found varying degrees of failure/limited success, but for me this approached seemed to work the best within the confines of Helm and the current image release (1.9.3), with some of the attendant misfires and permission issues we ground through.

If you have any questions, please reach out. Hopefully, this helps.
