### ISSUE TITLE
Kubernetes Auth Method is not working on kubenetes 1.6 version

### ISSUE THREAD

**Issue by olx-shashank-singh** [hashicorp/vault#6657]
Why Kubernetes auth method is not working on openshift version less than or equal to 3.6 version (Which is using kubernetes 1.6 version). While making logging request, It throws an error: 
`the server could not find the requested resource`.

It's working fine with above Kubernetes/Openshift versions.

Anyone have any idea regarding this.
Thanks!

**Comment by jasonodonnell** [comment]
This may be caused by the plugin using [TokenReview objects](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/token_review.go#L65-L69).  I believe those were introduced in 3.7 OpenShift.

**Comment by briankassouf** [comment]
Yep, the auth method requires the TokenReview API, therefore it will not work with kubernetes 1.6

**Comment by olx-shashank-singh** [comment]
@briankassouf I know that kubernetes auth method requires the TokenReview API but I have created the `system:auth-delegator` cluster role as  below. 
```
apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:auth-delegator
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
```

After creating this role and attached it to service account then also it's not working.

Also we have `system:node` & `cluster-reader` Cluster role in RBAC in Kubernetes 1.6 having TokenReview API like this:
```
[create]		[]			[]		[authentication.k8s.io]	[tokenreviews]
```
 then also it's not working.

Can you please explain why this happening after having TokenReview API?
