### ISSUE TITLE
Vault behind ELB Loop Redirects prevent from logging in

### ISSUE THREAD

**Issue by jaybe78** [hashicorp/vault#6881]
Hi,

I have created a dedicated kubernetes cluster for consul and vault in AWS.

My cluster has 3 instances vault and all of them are currently running which means, I've unsealed vault in every single instance

Vault instances are exposed through an AWS NLB.

<img width="325" alt="Screenshot 2019-06-14 at 01 07 03" src="https://user-images.githubusercontent.com/3605098/59476062-e3aafe80-8e46-11e9-82b7-342fcc079934.png">

When logging via web ui or command line I get: 

<img width="1487" alt="Screenshot 2019-06-14 at 01 09 03" src="https://user-images.githubusercontent.com/3605098/59476092-f6253800-8e46-11e9-8274-8deca424432c.png">

**_Note:_** I've found out that if I seal 2 of vault instance and leave one unsealed, I'm able to log in.

So is vault supposed to run only one replica at the same time ?

Will it unseal automatically one the other instance if the current leader fails ?

Please check my vault statefulset's config

```
- name: VAULT_LOCAL_CONFIG
          value:
            api_addr     = "https://$(LOAD_BALANCER_ADDR)"
            cluster_addr = "https://$(POD_IP_ADDR):8201"
            log_level = "warn"
            ui = true
            backend "consul" {
              address = "127.0.0.1:8500"
              redirect_addr = "https://$(LOAD_BALANCER_ADDR):8200"
              cluster_addr = "https://$(VAULT_1_SERVICE_HOST):$(VAULT_1_SERVICE_PORT_BACKENDPORT)"
              token = "$(VAULT_CONSUL_KEY)"
              disable_registration = "false"
            }

            listener "tcp" {
              address     = "127.0.0.1:8200"
              tls_disable = "true"
            }
            listener "tcp" {
              address       = "$(POD_IP_ADDR):8200"
              tls_cert_file = "/etc/vault/tls/tls.crt"
              tls_key_file  = "/etc/vault/tls/tls.key"
              tls_disable_client_certs = true
            }
        args:
        - "server"
        ports:
        - name: vault-port
          containerPort: 8200
          protocol: TCP
        - name: cluster-port
          containerPort: 8201
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "/v1/sys/health?standbyok=true"
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
```

vault service

```
kind: Service
apiVersion: v1
metadata:
  name: vault-lb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: vault
  ports:
  - name: vault-port
    port: 443
    targetPort: 8200
    protocol: TCP
```
