### ISSUE TITLE
Vault fails to communicate with etcd cluster behind a Azure App Gateway

### ISSUE THREAD

**Issue by fazlearefin** [hashicorp/vault#7001]
**Describe the bug**
I have a vault server (`vaultvm01`) where etcd is used as the backend. There are a total of 3 etcd (`etcdvm01, etcdvm02, etcdvm03`) nodes. An Azure App Gateway (Layer 4 Load Balancer) is in front of the 3 etcd nodes. The vault server works fine when the backend servers are set as `etcdvm01, etcdvm02, etcdvm03` so that vault can communicate with the etcd nodes directly. But when the vault server uses the Azure App Gateway endpoint, `etcdgw.example.com`, it fails.

**To Reproduce**
1. Start vault with Azure App Gateway endpoint as the backend storage

**Expected behavior**
Vault should start up and should be able to retried data from backend etcd storage.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.3
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.3 ('9bc820f700f83a7c4bcab54c5323735a581b34eb')
* Server Operating System/Architecture: vault:latest docker image running on CentOS 7.5.1804

Vault server configuration file(s):

```hcl
ui = true

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = "false"
  tls_cert_file = "/etc/ipa/host.crt"
  tls_key_file = "/etc/ipa/host.key"
  tls_min_version = "tls12"
  tls_cipher_suites = "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
}

storage "etcd" {
  # commented out setting below works fine
  #address = "https://etcdvm01.example.com:2379,https://etcdvm02.example.com:2379,https://etcdvm03.example.com:2379"
  # this setting below does not work
  address = "https://etcdgw.example.com"
  tls_ca_file = "/etc/ipa/ca.crt"
  etcd_api = "v3"
  ha_enabled = "true"
  path = "/vault/"
}

api_addr = "https://0.0.0.0:8200"
disable_clustering = true
```

**Additional comments**

etcd version: 3.3.13

This is the error when the Azure App Gateway (etcdgw.example.com) is used: `Error initializing storage of type etcd: context deadline exceeded`

This is the `docker-compose.yml` file I am using:

```
[user@vaultvm01 vaultdocker]$ cat docker-compose.yml
---
version: "3.7"

services:
  vaultdocker:
    container_name: vaultdocker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /etc/ipa:/etc/ipa
      - /var/log/vault:/vault/logs
      - /etc/vault:/vault/config
    cap_add:
      - IPC_LOCK
    command:
      - vault
      - server
      - -config
      - /vault/config/vault-config.hcl

    network_mode: host
    restart: always

[user@vaultvm01 vaultdocker]$
```

And this is the error I am getting when running the vault docker image:

```bash
[user@vaultvm01 vaultdocker]$ sudo docker-compose up
Creating vaultdocker ... done
Attaching to vaultdocker
vaultdocker    | Error initializing storage of type etcd: context deadline exceeded
vaultdocker exited with code 1
[user@vaultvm01 vaultdocker]$
```

---

From the vault server (`vaultvm01`), there is no connectivity issue to the Azure App Gateway:
```bash
[user@vaultvm01 ~]$ curl -s https://etcdgw.example.com/health | jq
{
  "health": "true"
}
[user@vaultvm01 ~]$ curl -s https://etcdgw.example.com/version | jq
{
  "etcdserver": "3.3.13",
  "etcdcluster": "3.3.0"
}
[user@vaultvm01 ~]$
```
