### ISSUE TITLE
docker-compose - random 500 and then success

### ISSUE THREAD

**Issue by zachgersh** [hashicorp/vault#782]
Hey all,

I am sure I am doing something just slightly wrong here.  Can't seem to get vault to connect to my consul server.

I am using the `--x-networking` flag (hence no links)

docker-compose file
```
resource:
  build: .
  command: echo "foo"
  volumes:
    - .:/source
vault:
  build: ./vault
  ports:
    - 8200:8200
  volumes:
    - ./vault/vault-config.hcl:/tmp/vault.hcl
  volumes_from:
    - consul
  command: "server -dev -config=/tmp/vault.hcl"
consul:
  image: gliderlabs/consul
  ports:
    - 8500:8500
  volumes:
    - ./vault/consul-config.json:/tmp/consul.json
  command: "agent -config-file=/tmp/consul.json"
```

consul config
```js
{
  "data_dir": "dc1",
  "server": true,
  "bootstrap": true,
  "ui_dir": "/ui"
}
```

vault config
```
backend "consul" {
  address = "vaultresource_consul_1:8500"
  advertise_addr = "http://127.0.0.1"
  path = "vault"
}

listener "tcp" {
  address = "0.0.0.0:8201"
  tls_disable = 1
}

disable_mlock = true
```

log output from the start
```
consul_1 | ==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
consul_1 | ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
consul_1 | ==> Starting Consul agent...
consul_1 | ==> Starting Consul agent RPC...
consul_1 | ==> Consul agent running!
consul_1 |          Node name: 'consul'
consul_1 |         Datacenter: 'dc1'
consul_1 |             Server: true (bootstrap: true)
consul_1 |        Client Addr: 0.0.0.0 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
consul_1 |       Cluster Addr: 172.18.0.2 (LAN: 8301, WAN: 8302)
consul_1 |     Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
consul_1 |              Atlas: <disabled>
consul_1 |
consul_1 | ==> Log data will now stream in as it occurs:
consul_1 |
consul_1 |     2015/11/17 06:30:41 [INFO] serf: EventMemberJoin: consul 172.18.0.2
consul_1 |     2015/11/17 06:30:41 [INFO] serf: EventMemberJoin: consul.dc1 172.18.0.2
consul_1 |     2015/11/17 06:30:41 [INFO] raft: Node at 172.18.0.2:8300 [Follower] entering Follower state
consul_1 |     2015/11/17 06:30:41 [INFO] consul: adding server consul (Addr: 172.18.0.2:8300) (DC: dc1)
consul_1 |     2015/11/17 06:30:41 [INFO] consul: adding server consul.dc1 (Addr: 172.18.0.2:8300) (DC: dc1)
consul_1 |     2015/11/17 06:30:41 [ERR] agent: failed to sync remote state: No cluster leader
consul_1 |     2015/11/17 06:30:41 [ERR] http: Request /v1/kv/vault/core/keyring, error: No cluster leader
consul_1 |     2015/11/17 06:30:42 [WARN] raft: Heartbeat timeout reached, starting election
consul_1 |     2015/11/17 06:30:42 [INFO] raft: Node at 172.18.0.2:8300 [Candidate] entering Candidate state
consul_1 |     2015/11/17 06:30:42 [INFO] raft: Election won. Tally: 1
consul_1 |     2015/11/17 06:30:42 [INFO] raft: Node at 172.18.0.2:8300 [Leader] entering Leader state
consul_1 |     2015/11/17 06:30:42 [INFO] consul: cluster leadership acquired
consul_1 |     2015/11/17 06:30:42 [INFO] consul: New leader elected: consul
consul_1 |     2015/11/17 06:30:42 [INFO] raft: Disabling EnableSingleNode (bootstrap)
consul_1 |     2015/11/17 06:30:42 [INFO] consul: member 'consul' joined, marking health alive
consul_1 |     2015/11/17 06:30:43 [INFO] agent: Synced service 'consul'
vault_1  | Error initializing dev mode: failed to check for initialization: Unexpected response code: 500\
```

**Comment by jsok** [comment]
You probably want to add a `links` section to your `vault` container like:

```yaml
vault:
  build: ./vault
  links:
    - consul
 ... etc
```

And then docker will create an entry in `/etc/hosts` for the host `consul` pointing at the IP of the consul container.

Therefore you new vault config will be:

```hcl
backend "consul" {
  address = "consul:8500"
  ... etc
}
```
