### ISSUE TITLE
v1/sys/metrics endpoint doesn't work with format=prometheus parameter

### ISSUE THREAD

**Issue by balusarakesh** [hashicorp/vault#7903]
**Describe the bug**
I'm trying to monitor vault with prometheus-operator. When I make a request to the endpoint `/v1/sys/metrics?format=prometheus` I get `err="server returned HTTP status 400 Bad Request"`
According to the documentation https://www.vaultproject.io/docs/configuration/telemetry.html I'm specifying the format parameter in my serviceMonitor.yaml like this
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: vault
  name: vault
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  endpoints:
    - interval: 30s
      path: /v1/sys/metrics
      params:
        format: 
          - prometheus
      port: http
      scheme: http
      scrapeTimeout: 30s
      bearerTokenFile: /etc/prometheus/config_out/.vault-token

```

**To Reproduce**
I followed the documentation here - https://medium.com/@mwieczorek/yet-another-vault-monitoring-with-prometheus-blog-post-f525c862baca

**Expected behavior**
I expect the metrics to be seen in prometheus format when `format=prometheus` is specified

**Environment:**
```
/ # vault status
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    5
Threshold                3
Version                  1.2.2
Cluster Name             vault-cluster-40da9a5f
Cluster ID               CLUSTER_ID
HA Enabled               true
HA Cluster               https://172.18.25.245:8201
HA Mode                  standby
Active Node Address      http://172.18.25.245:8200
```
* Vault CLI Version `v1.2.2`

Vault server configuration file(s):

```
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "dynamodb" {
  ha_enabled = "true"
  region = "us-west-2"
  table = "qa-us-west-2-app-vault"
}

seal "awskms" {
  region = "us-west-2"
  kms_key_id = "KMS_ID"
}
```

**Additional context**
```
/prometheus $ wget  --header='Authorization: Bearer TOKEN_HERE'  http://172.18.18.0:8200/v1/sys/metrics?format=prometheus
Connecting to 172.18.18.0:8200 (172.18.18.0:8200)
wget: server returned error: HTTP/1.1 400 Bad Request
```

**Comment by michelvocks** [comment]
Hi @balusarakesh!

By default, Prometheus metrics are disabled. Have you tried to enable them?
Adding the lines below to your Vault configuration should do the trick.

```
telemetry {
  prometheus_retention_time = "30s"
  disable_hostname = true
}
```

Cheers,
Michel

**Comment by balusarakesh** [comment]
@michelvocks 
I've updated the vault config to the following and I still get the same error `wget: server returned error: HTTP/1.1 400 Bad Request`
```
/ # cat /vault/config/extraconfig-from-values.hcl
ui = true
telemetry {
  prometheus_retention_time = "24h"
  disable_hostname = true
}

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "dynamodb" {
  ha_enabled = "true"
  region = "us-west-2"
  table = "qa-us-west-2-app-vault"
}

seal "awskms" {
  region = "us-west-2"
  kms_key_id = "KMS_ID"
}
```

**Comment by michelvocks** [comment]
Did you restart your Vault instance? The change should be active after a restart.

Also, is it possible to use curl instead of wget? It should print out the returned error message:
`curl -v -H 'X-Vault-Token: <token>' http://127.0.0.1:8200/v1/sys/metrics\?format=prometheus`

**Comment by balusarakesh** [comment]
it works when the header is `X-Vault-Token:`

**Comment by balusarakesh** [comment]
it started working today, not sure what changed

**Comment by balusarakesh** [comment]
we are still looking into it

**Comment by balusarakesh** [comment]
re-building the cluster seems to have fixed the issue

**Comment by bastelfreak** [comment]
Hi people,
I run into a similar issue with vault 1.5.5 and vault 1.5.7 yesterday. After a few hours prometheus stopped working and logged http 400 errors. I had the vault-agent running on the prometheus server. the agent did the approle authentication and provided the bearer_file for prometheus. prometheus scraped the metrics from the active vault server (7 node cluster). 

I wasn't able to figure out why it fails. the active vault server didn't log anything for the http 400 errors. I now updated the configuration and prometheus scrapes the metrics from the vault-agent. that automatically forwards the requests to the active vault server. the vault-agent provides a http listener on localhost so no  bearer token/file is required for prometheus. maybe that helps other people as well.

**Comment by tks98** [comment]
I ran into this problem today. My issue was with the service/podmonitor config. Vault was sending the 400 error back due to sending http request to the https metrics endpoint.

Hacky way around is to set the scheme to https and set the TLS config to accept untrusted certs

```yaml
 - port: api-port
      scheme: HTTPS
      tlsConfig:
        insecureSkipVerify: true
      interval: 15s
      path: /v1/sys/metrics
      params:
        format: 
          - prometheus
 ```

But ideally you specify the correct configuration options for the [tlsConfig](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.TLSConfig). 

After doing this, my serviceMonitor was able to get metrics from Vault.
