### ISSUE TITLE
Invalid Yaml in configmap injection

### ISSUE THREAD

**Issue by b-odonoghue** [hashicorp/vault#8104]
Hello,

It looks like there is an error in the in the configmap example documentaion which can be found [here](https://github.com/hashicorp/vault/blob/HEAD@%7B2020-01-07T01:09:29Z%7D/website/source/docs/platform/k8s/injector/examples.html.md#configmap-example)

There is a block that currently shows 
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
agent-config
    app: app-example
data:
  config.hcl: |
```

But that is clearly invalid yaml, though I am honestly not sure what the correct form is.

Adding a colon is wrong as agent-config is not something that Kubernetes understands.
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
agent-config:
    app: app-example
data:
  config.hcl: |
```
