### ISSUE TITLE
GCP: Vault 1.4 crashes on start-up with KMS unseal

### ISSUE THREAD

**Issue by jpds** [hashicorp/vault#8821]
I use Vault on Google Cloud Platform with KMS auto-unseal and a cloud storage bucket for the backend. I also use the Vault Docker image.

This ran fine with Vault 1.3.3, I upgraded to 1.4.0 and my Vault containers fail with the below log output.

I downgraded back to 1.3.4 and my containers were able to start again.

**Environment:** GCP

* Vault Version: 1.4.0

**Vault Config File:**

```
{"api_addr":"http://vault.company","listener":{"tcp":{"address":"[::]:8200","cluster_address":"[::]:8201","tls_disable":true}},"storage":{"gcs":{"bucket":"vault-store-string","ha_enabled":"true"}},"ui":true}
```

```
      extraEnv:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/vault/sa/key.json"
      - name: GOOGLE_PROJECT
        value: "project-name"
      - name: GOOGLE_REGION
        value: "us-east1"
      - name: VAULT_GCPCKMS_SEAL_KEY_RING
        value: "company-keyring"
      - name: VAULT_GCPCKMS_SEAL_CRYPTO_KEY
        value: "company-key"
      - name: VAULT_SEAL_TYPE
        value: "gcpckms"
```

**Startup Log Output:**

```text
production-vault/vault-6ccdc569d-nsmnc[vault]: goroutine 1 [running]:
production-vault/vault-6ccdc569d-nsmnc[vault]: github.com/hashicorp/vault/command/server/seal.configureGCPCKMSSeal(0xc0006a7280, 0xc0006a7260, 0xc00000ead0, 0x3e3c240, 0xc000860840, 0x3e3e100, 0xc0006a72c0, 0x305aae0, 0x305aae0, 0xc000d51258, ...)
production-vault/vault-6ccdc569d-nsmnc[vault]:  /go/src/github.com/hashicorp/vault/command/server/seal/server_seal_gcpckms.go:16 +0x86
production-vault/vault-6ccdc569d-nsmnc[vault]: github.com/hashicorp/vault/command/server/seal.configureSeal(0xc0006a7280, 0xc0006a7260, 0xc00000ead0, 0x3e3c240, 0xc000860840, 0x3e3e100, 0xc0006a72c0, 0x1, 0x0, 0x0, ...)
production-vault/vault-6ccdc569d-nsmnc[vault]:  /go/src/github.com/hashicorp/vault/command/server/seal/server_seal.go:28 +0x4ca
production-vault/vault-6ccdc569d-nsmnc[vault]: github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc0000c6160, 0xc00004c0e0, 0x2, 0x2, 0x0)
production-vault/vault-6ccdc569d-nsmnc[vault]:  /go/src/github.com/hashicorp/vault/command/server.go:1039 +0x139f
production-vault/vault-6ccdc569d-nsmnc[vault]: github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc000362a00, 0xc000362a00, 0xc0002f7ea0, 0xc0002f7da0)
production-vault/vault-6ccdc569d-nsmnc[vault]:  /go/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
production-vault/vault-6ccdc569d-nsmnc[vault]: github.com/hashicorp/vault/command.RunCustom(0xc00004c0d0, 0x3, 0x3, 0xc0000b1900, 0xc00008e058)
production-vault/vault-6ccdc569d-nsmnc[vault]:  /go/src/github.com/hashicorp/vault/command/main.go:180 +0x858
production-vault/vault-6ccdc569d-nsmnc[vault]: github.com/hashicorp/vault/command.Run(...)
production-vault/vault-6ccdc569d-nsmnc[vault]:  /go/src/github.com/hashicorp/vault/command/main.go:88
production-vault/vault-6ccdc569d-nsmnc[vault]: main.main()
production-vault/vault-6ccdc569d-nsmnc[vault]:  /go/src/github.com/hashicorp/vault/main.go:10 +0x71
```
