### ISSUE TITLE
raft.retry_rejoin stanza seems to be expecting certificate strings instead of certificate paths

### ISSUE THREAD

**Issue by raffaelespazzoli** [hashicorp/vault#9075]
**Describe the bug**
It's unclear from the docs, but based on discussions found of forums and the behavior of the product, it looks like in the `raft.retry_rejoin` stanza the tls configuration actually expects the certificate strings not the certificate file paths...

What would be the notation to put the certificate string in that field?

Also this seems wrong and those should probably be paths like for the other tls configurations.

Finally while the meaning of the fields is clear, the way they are going to be used in unclear. In particular the fact that we are passing a client certs seems to imply that we are going to establish mTLS when the raft peers are talking. Yet, on the server side of the communication it is unclear against what the client cert will be validated.

**To Reproduce**
I have a certificate created this way with cert-manager, which will be used by all the peers of the cluster:

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vault
spec:
  # Secret names are always required.
  secretName: vault-tls
  commonName: vault
  usages:
    - server auth
    - client auth  
  dnsNames:
  - vault-0.vault-internal
  - vault-1.vault-internal
  - vault-2.vault-internal
  - vault
  issuerRef:
    name: internal-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io    
```
this cert is mounted on all of the peers at `/etc/vault-tls/vault-tls`.
here is the relevant configuration of the raft stanza

```hcl
        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert = "/etc/vault-tls/vault-tls/ca.crt"
            leader_client_cert = "/etc/vault-tls/vault-tls/tls.crt"
            leader_client_key = "/etc/vault-tls/vault-tls/tls.key"
          }

          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_ca_cert = "/etc/vault-tls/vault-tls/ca.crt"
            leader_client_cert = "/etc/vault-tls/vault-tls/tls.crt"
            leader_client_key = "/etc/vault-tls/vault-tls/tls.key"
          }
                  
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_ca_cert = "/etc/vault-tls/vault-tls/ca.crt"
            leader_client_cert = "/etc/vault-tls/vault-tls/tls.crt"
            leader_client_key = "/etc/vault-tls/vault-tls/tls.key"
          }

        }
```

here is the error I see:

```log
==> Vault server configuration:

               Seal Type: transit
         Transit Address: https://seed-vault:8200
        Transit Key Name: unseal_key
      Transit Mount Path: transit/
             Api Address: https://10.128.2.44:8200
                     Cgo: disabled
         Cluster Address: https://vault-0.vault-internal:8201
              Listener 1: tcp (addr: "[::]:8200", cluster address: "[::]:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
               Log Level: debug
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: raft (HA available)
                 Version: Vault v1.4.2

Failed to initiate raft retry join, "failed to create tls config to communicate with leader node \"https://vault-0.vault-internal:8200\": tls: failed to find any PEM data in certificate input"
```

at which point the server crashes

notice that if I comment the cert and key fields in the retry_rejoin stanza, vault does not crash but automatic rejoin does not work.

notice that manual join works with this command line (in which you can see that the cert is passed as a string not as a file path):

```shell
oc exec vault-1 -n vault -- sh -c 'vault operator raft join -address https://vault-1.vault-internal:8200 -ca-path /etc/vault-tls/vault-tls/ca.crt -leader-ca-cert="`cat /etc/vault-tls/vault-tls/ca.crt`" https://vault-0.vault-internal:8200'
oc exec vault-2 -n vault -- sh -c 'vault operator raft join -address https://vault-2.vault-internal:8200 -ca-path /etc/vault-tls/vault-tls/ca.crt -leader-ca-cert="`cat /etc/vault-tls/vault-tls/ca.crt`" https://vault-0.vault-internal:8200'
```

**Expected behavior**
instances should auto join the cluster

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.2
* Vault CLI Version (retrieve with `vault version`): 1.4.2
* Server Operating System/Architecture: RedHat Core OS, OpenShif, Vault running as a container

Vault server configuration file(s):

```hcl
    disable_mlock = true
    ui = true

    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_cert_file="/etc/vault-tls/vault-tls/tls.crt"
      tls_key_file="/etc/vault-tls/vault-tls/tls.key"
      tls_client_ca_file="/etc/vault-tls/vault-tls/ca.crt"          
    }

    seal "transit" {
      address            = "https://seed-vault:8200"
      token              = "XXXXXXXXXXXXXXXXXX"
      disable_renewal    = "false"

      // Key configuration
      key_name           = "unseal_key"
      mount_path         = "transit/"      
      tls_ca_cert        = "/etc/vault-tls/seed-vault-tls/ca.crt"
                
    }
    storage "raft" {
      path = "/vault/data"

      retry_join {
        leader_api_addr = "https://vault-0.vault-internal:8200"
        leader_ca_cert = "/etc/vault-tls/vault-tls/ca.crt"
        leader_client_cert = "/etc/vault-tls/vault-tls/tls.crt"
        leader_client_key = "/etc/vault-tls/vault-tls/tls.key"
      }

      retry_join {
        leader_api_addr = "https://vault-1.vault-internal:8200"
        leader_ca_cert = "/etc/vault-tls/vault-tls/ca.crt"
        leader_client_cert = "/etc/vault-tls/vault-tls/tls.crt"
        leader_client_key = "/etc/vault-tls/vault-tls/tls.key"
      }
              
      retry_join {
        leader_api_addr = "https://vault-2.vault-internal:8200"
        leader_ca_cert = "/etc/vault-tls/vault-tls/ca.crt"
        leader_client_cert = "/etc/vault-tls/vault-tls/tls.crt"
        leader_client_key = "/etc/vault-tls/vault-tls/tls.key"
      }

    }

    log_level = "debug"

    service_registration "kubernetes" {}
```
