### ISSUE TITLE
AGENT_INJECT_SET_SECURITY_CONTEXT not honored

### ISSUE THREAD

**Issue by raffaelespazzoli** [hashicorp/vault#9165]
**Describe the bug**

I'm configuring the agent with the following environment variable:
`AGENT_INJECT_SET_SECURITY_CONTEXT=false`
My understanding is that with this configuration the agent will not inject a security context in the injected containers.
But as far as I can see a security context is still being injected in both the initcontainer and container, here is the error that I get:
```
unable to validate against any security context constraint: [spec.initContainers[0].securityContext.securityContext.runAsUser: Invalid value: 100: must be in the ranges: [1000640000, 1000649999] spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 100: must be in the ranges: [1000640000, 1000649999]]
```

in this particular cluster there are constraints on which uids can be used. not injecting a security context would make sure that the constraints are met.

Also the annotation seems to be disregarded: `vault.hashicorp.com/agent-set-security-context: "false"`, does not have any effect.

both the environment variable and the annotation are referenced here: https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-set-security-context

**To Reproduce**
1. set `AGENT_INJECT_SET_SECURITY_CONTEXT=false` on the agent mutating webhook pod. 
2. try to inject the agent on any default namespace in OpenShift (they will have the restrcuted uid intervals)
3. See that the pods are not being deployed.

**Expected behavior**
no security context is injected, the pods are deployed correclty.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
vault status -tls-skip-verify
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.4.2
Cluster Name             vault-cluster-69ba6bdd
Cluster ID               8f0c227b-c2a3-286f-3314-52a6135617f5
HA Enabled               true
HA Cluster               https://vault-0.vault-internal:8201
HA Mode                  active
Raft Committed Index     91
Raft Applied Index       91
```
* Vault CLI Version (retrieve with `vault version`):
```
vault version
Vault v1.4.2
```
* Server Operating System/Architecture:
OpenShift 4.4

Vault server configuration file(s):

I install vault via the helm chart, this is my values file

```yaml
global:
  tlsDisable: false
ui:
  enabled: true
server:
  extraSecretEnvironmentVars:
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-aws-kms-credentials
      secretKey: aws_secret_access_key
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-aws-kms-credentials
      secretKey: aws_access_key_id      
  image:
    tag: "1.4.2"
  extraVolumes:
    - type: 'secret'
      name: 'vault-tls'
      path: '/etc/vault-tls'        
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file="/etc/vault-tls/vault-tls/tls.crt"
          tls_key_file="/etc/vault-tls/vault-tls/tls.key"
          tls_client_ca_file="/etc/vault-tls/vault-tls/ca.crt"          
        }

        seal "awskms" {
          region     = "${region}"
          kms_key_id = "${key_id}"
        }

        storage "raft" {
          path = "/vault/data"
  
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file = "/etc/vault-tls/vault-tls/ca.crt"
            #leader_client_cert_file = "/etc/vault-tls/vault-tls/tls.crt"
            #leader_client_key_file = "/etc/vault-tls/vault-tls/tls.key"
          }

          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_ca_cert_file = "/etc/vault-tls/vault-tls/ca.crt"
            #leader_client_cert_file = "/etc/vault-tls/vault-tls/tls.crt"
            #leader_client_key_file = "/etc/vault-tls/vault-tls/tls.key"
          }
                  
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_ca_cert_file = "/etc/vault-tls/vault-tls/ca.crt"
            #leader_client_cert_file = "/etc/vault-tls/vault-tls/tls.crt"
            #leader_client_key_file = "/etc/vault-tls/vault-tls/tls.key"
          }

        }

        log_level = "debug"

        service_registration "kubernetes" {}  
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: vault
              app.kubernetes.io/instance: vault
              component: server
          topologyKey: failure-domain.beta.kubernetes.io/zone        
injector:
  agentImage:
    tag: "1.4.2"
  extraEnvironmentVars: 
    AGENT_INJECT_SET_SECURITY_CONTEXT: "true"
```

here is how I'm trying to inject the agent:
```yaml
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Release.Namespace }}
        vault.hashicorp.com/agent-set-security-context: "false"
```

**Comment by raffaelespazzoli** [comment]
found the issue. This is the correct configuration of the injector:
```
injector:
  image:
    tag: "0.4.0"
  agentImage:
    tag: "1.4.2"
  extraEnvironmentVars: 
    AGENT_INJECT_SET_SECURITY_CONTEXT: "false"
```
I recommend updating the helm chart default.
we can close this.
