### ISSUE TITLE
Vault Proxy Protocol support is broken on Google Cloud

### ISSUE THREAD

**Issue by upodroid** [hashicorp/vault#9462]
**Describe the bug**

Vault fails to pass Google Health Checks that have proxy protocol enabled. Google Support investigated this and concluded with the following:

The product team found out that vault is not prepared to handle PROXY1V_UNKNOWN string. That is why the healthchecks were failing.

I will share the findings below:

https://github.com/hashicorp/vault/blob/3831cbfac99222866c0f4eb3b9f563f37e2852aa/command/server/listener.go#L43 - vault proxy protocol setup

https://github.com/hashicorp/vault/blob/3831cbfac99222866c0f4eb3b9f563f37e2852aa/helper/proxyutil/proxyutil.go#L9 - proxy protocol implemented in first link - which can handle the `unknown` string - https://github.com/armon/go-proxyproto/blob/f0b8253b1507a570415b16910691d11751a0685c/protocol.go#L52 , but doesn't, as can be seen in proxyutil.go

Given that the healthcheck failed due to vault not being prepared to receive the "UNKNOWN" string, we will not pursue this as a fixable issue.

**To Reproduce**
1. Deploy Google Cloud LB with a Google HC that has the following config.
```
checkIntervalSec: 1
creationTimestamp: '2020-06-28T13:37:23.358-07:00'
description: ''
healthyThreshold: 2
http2HealthCheck:
  host: vault.upo.one
  port: 8200
  proxyHeader: PROXY_V1
  requestPath: /v1/sys/health
id: '471244148877640044'
kind: compute#healthCheck
logConfig:
  enable: true
name: vault-hc
selfLink: https://www.googleapis.com/compute/v1/projects/REDACTED/global/healthChecks/vault-hc
timeoutSec: 1
type: HTTP2
unhealthyThreshold: 2
```

**Expected behavior**
It should work but SSL failures happen.

App Log:

```
{"@level":"info","@message":"http: TLS handshake error from 130.211.0.205:45346: read tcp 10.100.0.20:8200-\u003e130.211.0.205:45346: use of closed network connection","@timestamp":"2020-06-29T09:34:20.480293Z"}
2020-06-29 09:34:20.742588 I | [ERR] Failed to read proxy prefix: Invalid header line: PROXY UNKNOWN
{"@level":"info","@message":"http: TLS handshake error from 130.211.0.201:44978: read tcp 10.100.0.20:8200-\u003e130.211.0.201:44978: use of closed network connection","@timestamp":"2020-06-29T09:34:20.742655Z"}
2020-06-29 09:34:20.751224 I | [ERR] Failed to read proxy prefix: Invalid header line: PROXY UNKNOWN
{"@level":"info","@message":"http: TLS handshake error from 130.211.3.46:51922: read tcp 10.100.0.20:8200-\u003e130.211.3.46:51922: use of closed network connection","@timestamp":"2020-06-29T09:34:20.751287Z"}
Local HTTP request:
```
Vault server configuration file(s):

```hcl
# Run Vault in HA mode. Even if there's only one Vault node, it doesn't hurt to
# have this set.
api_addr = "{{ api_addr }}"
cluster_addr = "https://{{ ansible_all_ipv4_addresses[0]  }}:8201"

# Set debugging level
log_level = "{{vault_log_level}}"
log_format = "json"

# Enable the UI
ui = {{ vault_ui_enabled | to_json }}

# Enable plugin directory
plugin_directory = "/etc/vault.d/plugins"

# Enable auto-unsealing with Google Cloud KMS
seal "gcpckms" {
  project    = "{{ kms_project }}"
  region     = "{{ kms_location }}"
  key_ring   = "{{ kms_keyring }}"
  crypto_key = "{{ kms_crypto_key }}"
}

# Enable HA backend storage with GCS
storage "gcs" {
  bucket     = "{{ storage_bucket }}"
  ha_enabled = "true"
}

# Create local non-TLS listener
listener "tcp" {
  address     = "127.0.0.1:{{ vault_port }}"
  tls_disable = "true"
}


# Create an mTLS listener locally. Client's shouldn't talk to Vault directly,
# but not all clients are well-behaved. This is also needed so the nodes can
# communicate with eachother.
listener "tcp" {
  address            = "{{ ansible_all_ipv4_addresses[0] }}:{{vault_port}}"
  tls_cert_file      = "/etc/vault/vault.crt"
  tls_key_file       = "/etc/vault/vault.key"
  #tls_client_ca_file = "/etc/vault/ca.crt"
  proxy_protocol_behavior = "use_always"

  tls_disable_client_certs           = {{ vault_tls_disable_client_certs | to_json }}
  tls_require_and_verify_client_cert = {{ vault_tls_require_and_verify_client_cert | to_json }}
}

# Send data to Stackdriver monitoring
telemetry {
  stackdriver_project_id = "{{ kms_project }}"
  stackdriver_location = "{{ ansible_domain.split(".")[0] | zone_to_region }}"
  stackdriver_namespace = "vault"
  disable_hostname = true
  enable_hostname_label = true
}

```

**Additional context**
